### ISSUE TITLE
[Feature Request] Write a plugin for mirroring

### ISSUE THREAD

**Issue by rubyconvict** [shrinerb/shrine#174]
See the mirroring feature introduced in rails/activestorage.
Described here: http://afreshcup.com/home/2017/7/6/introduction-to-active-storage-part-4-mirroring.html
Source: https://github.com/rails/activestorage

**Comment by janko-m** [comment]
Thanks for opening this ticket. I would like to make this as a separate gem, so that it can be used in a similar way as in ActiveStorage. For example, if you're using S3 as permanent storage, and you want to add Google Cloud Storage as the secondary, it would like like this:

```rb
require "shrine"
require "shrine/storage/file_system"
require "shrine/storage/s3"
require "shrine/storage/google_cloud_storage"
require "shrine/storage/mirror"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"),
  store: Shrine::Storage::Mirror.new([
    Shrine::Storage::S3.new(**s3_options), # first storage is the primary storage
    Shrine::Storage::GoogleCloudStorage.new(**gcs_options),
  ])
}
```

What do you think? One downside is that upload speed will be slower, because every file will be uploaded to two storages synchronously. I would like the make the upload asynchronous, but two threads cannot upload the same IO object in parallel.

**Comment by rubyconvict** [comment]
Thank you for answering. Isn't that just the way the `parallelize` plugin works? I would like to see it: store the object normally using shrine (with any plugins you like) and then - just by adding the new plugin - schedule some background job that will just download/copy the already stored file (and it's versions) to any other storage one desires. Syncing replicas could be just a separate job (read active_job, sidekiq job or whatever) for each configured "replica". :relaxed:

**Comment by janko-m** [comment]
> Isn't that just the way the `parallelize` plugin works?

The `parallelize` plugin works for uploads to single storage, and is used to parallelize uploads when you're generating multiple versions.  That works normally, because all those files are different IO objects.

> I would like to see it: store the object normally using shrine (with any plugins you like) and then - just by adding the new plugin - schedule some background job that will just download/copy the already stored file (and it's versions) to any other storage one desires.

I think the behaviour you're describing is that you can already do with the `backup` plugin. It just appeared to me that `ActiveStorage::Service::MirrorService` is a simpler solution.

**Comment by janko** [comment]
While preparing for Shrine 3.0, I've had the opportunity to give this more thought.

First, I believe that implementing a "mirror storage" akin to Active Storage's `MirrorService` would be far from ideal, as it would mean that mirroring would be happening synchronously. Likewise, doing automatic background mirroring like Active Storage does now would mean that the `backgrounding` plugin would need to know about mirroring.

Second, I believe the current `backup` plugin is the wrong way to go as well. It hooks into the `Attacher`, so it won't work when the uploader is used directly, and it works synchronously. While improving the attacher API for Shrine 3.0, I realized we won't be able to keep it working in the same way. The `backup` plugin will get deprecated and removed in Shrine 3.0.

However, I've recently added a new `instrumentation` plugin, which allows users to implement mirroring themselves, and with good performance characteristics. Here is an example of hooking into upload & delete events and mirroring S3 uploads to GCS in a background job:

```rb
Shrine.storages = {
  cache: Shrine::Storage::S3.new(...),
  store: Shrine::Storage::S3.new(...),
  gcs: Shrine::Storage::GoogleCloudStorage.new(...),
}

Shrine.plugin :instrumentation

Shrine.subscribe(:upload) do |event|
  next if event[:storage] != :store # mirror only uploads on permanent storage

  Attachment::MirrorUpload.perform_async(
    event[:uploader],
    event[:location],
    event[:storage],
    :gcs,
  )
end

Shrine.subscribe(:delete) do |event|
  next if event[:storage] != :store # mirror only deletes on permanent storage

  Attachment::MirrorDelete.perform_async(
    event[:uploader],
    event[:location],
    :gcs,
  )  
end
```
```rb
class Attachment::MirrorUpload
  include Sidekiq::Worker
  def perform(uploader_class, location, source_storage, mirror_storage)
    uploader_class = Object.const_get(uploader_class)
    uploaded_file = uploader_class.uploaded_file("storage" => source_storage, "id" => location)
    uploaded_file.download do |file|
      uploader_class.upload(file, mirror_storage, location: location)
    end
  end
end
```
```rb
class Attachment::MirrorDelete
  include Sidekiq::Worker
  def perform(uploader_class, location, mirror_storage)
     uploader_class = Object.const_get(uploader_class)
     uploaded_file = uploader_class.uploaded_file("storage" => mirror_storage, "id" => location)
     uploaded_file.delete
  end
end
```

I will put this up into a wiki page after Shrine 2.19.0 is released with the `instrumentation` plugin.

**Comment by janko** [comment]
Added – https://github.com/shrinerb/shrine/wiki/Mirroring-Uploads

Closing, as I believe this issue is now resolved.

**Comment by janko** [comment]
Shrine 3.0 will have a new [`mirroring`](https://github.com/shrinerb/shrine/blob/master/doc/plugins/mirroring.md#readme) plugin after all.
