### ISSUE TITLE
Plugin determine_mime_type not parsing xlsx files correctly

### ISSUE THREAD

**Issue by badosu** [shrinerb/shrine#259]
### Brief Description
When uploading `.xlsx` files the determine_mime_type plugin is not parsing it's mime type correctly.

### Expected behavior
Parsed mime type should be `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

### Actual behavior
It's returning `application/zip`. I tested all the other file analyzers with the same result.

### Simplest self-contained example code to demonstrate issue

```ruby
require "active_record"
require "shrine"
require "shrine/storage/file_system"
require "tmpdir"
require "open-uri"

Shrine.plugin :activerecord
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
}

class MyUploader < Shrine
  plugin :determine_mime_type
  plugin :validation_helpers

  Attacher.validate do
    validate_mime_type_inclusion %w[
      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    ], message: "Must be a valid Excel (.xlsx) file"
  end
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }
# make errors propagate when raised in callbacks
ActiveRecord::Base.raise_in_transactional_callbacks = true

class Post < ActiveRecord::Base
  include MyUploader::Attachment.new(:image)
end

Post.create!(image: open("http://www.nature.com/authorguide/sdata/Data-Descriptor-tables-template-for-authors.xlsx"))
```

### System configuration
**Ruby version**: 2.5.0
**Shrine version**: 2.9.0

**Comment by hmistry** [comment]
This might be related to https://github.com/mime-types/ruby-mime-types/issues/131.

**Comment by janko-m** [comment]
Shrine delegates analyzing MIME type to the underlying library, so if MIME type is determined incorrectly, that should be fixed in the underlying libraries.

In this case you can actually use the `:mime_types` analyzer which does determine the MIME type correctly:

```rb
plugin :determine_mime_type, analyzer: -> (io, analyzers) do
  mime_type = analyzers[:file].call(io)
  mime_type = analyzers[:mime_types].call(io) if mime_type == "application/zip"
  mime_type
end
```

**Comment by janko-m** [comment]
Note that the `:mime_types` analyzer will work only if the IO object has a known file extension. So in the self-contained script you posted it won't work, because `open-uri` doesn't keep the file extension from the URL, but it should work if you use Down:

```rb
require "down"
# ...
Post.create!(image: Down.download("http://www.nature.com/authorguide/sdata/Data-Descriptor-tables-template-for-authors.xlsx"))
```

**Comment by badosu** [comment]
Thank you @janko-m, I test here and indeed `mimetypes` works!

I overlooked it as there was this warning: "Note that unlike other solutions, this analyzer is not guaranteed to return the actual MIME type of the file."
