### ISSUE TITLE
Shrine processing plugin throws deprecation warnings

### ISSUE THREAD

**Issue by boboldehampsink** [shrinerb/shrine#266]
### Brief Description
The shrine-processing plugin throws ImageProcessing deprecation warnings

### Expected behavior
I expect the plugin to be updated to use the new chainable API

### Actual behavior
The plugin throws deprecation warnings: `[IMAGE_PROCESSING DEPRECATION WARNING] This API is deprecated and will be removed in ImageProcessing 1.0. Please use the new chainable API.`

### System configuration
**Ruby version**: 2.5.1

**Image processing version**: 0.11.2

**Shrine version**: 2.10.1

**Comment by janko-m** [comment]
The `processing` plugin has absolutely no knowledge of the ImageProcessing gem. It just executes the given block of code where you're expected to define your processing, it doesn't know what library you've used to perform the processing. In other words, Shrine and ImageProcessing are two completely separate gems.

You need to update the ImageProcessing code yourself to switch to the new API, see the [README](https://github.com/janko-m/image_processing#usage). You could also post your existing code here and I can convert it for you.

**Comment by boboldehampsink** [comment]
Ah, got it. Fixed already :-)
