### ISSUE TITLE
Access "current_user" in "generate_location".

### ISSUE THREAD

**Issue by johnunclesam** [shrinerb/shrine#274]
I'm using Shrine with Rails 5 and Devise just for test.

I don't know why it doesn't access the Devise's `current_user` in:

```ruby
class FileUploader < Shrine
  def generate_location(io, context)
    "student_profile/#{current_user}/#{super}"
  end
end
```

Is it possible to access `current_user` from there?

**Comment by janko-m** [comment]
Devise's `current_user` is a method defined only in your controllers, it won't be available in every class. You can forward the current user by updating `Shrine::Attacher#context`, e.g.

```rb
class StudentProfile < ActiveRecord::Base
  include FileUploader::Attachment.new(:file)
end
```

```rb
# in your controller
student_profile.assign_attributes(student_profile_params)
student_profile.file_attacher.context.update(current_user: current_user)
student_profile.save
```
```rb
class FileUploader < Shrine
  def generate_location(io, context)
    "student_profile/#{context[:current_user].id}/#{super}"
  end
end
```

This won't work with backgrounding unfortunately.

If you're doing direct uploads to S3 you should hopefully be able to access the current user through `env["warden"].user`:

```rb
plugin :presign_endpoint, presign_location: -> (request) do 
  "student_profile/#{request.env["warden"].user.id}/#{SecureRandom.hex}"
end
```

Note that usage questions should be asked on the Shrine Google Group, GitHub issues are intended only for bug reports, as per contribution guidelines.
