### ISSUE TITLE
Improve docs for multiple uploads

### ISSUE THREAD

**Issue by devkir** [shrinerb/shrine#276]
- Issues are for bug reports only.
- Have a question or unsure if it's a bug, then please inquire on the [ruby-shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine).
---

### Brief Description
Please update the docs for multiple uploads with Shrine and ActiveRecord. Currently there is no information what params should controller accept. How to validate presence of has_many :images on parent model. 

### Expected behavior
Better docs

### System configuration
**Ruby version**: 2.5.1

**Shrine version**: 2.1.1

**Comment by janko-m** [comment]
Note that the guide assumes you already know how ActiveRecord's [nested attributes](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html) work. But fair enough, I'll try to make the docs clearer.

> Currently there is no information what params should controller accept.

From the guide, these are the parameters that should be sent to the controller (for a `Album.has_many :photos` scenario):

```rb
album[photos_attributes][0][image] = '{"id":"38k25.jpg","storage":"cache","metadata":{...}}'
album[photos_attributes][1][image] = '{"id":"sg0fg.jpg","storage":"cache","metadata":{...}}'
album[photos_attributes][2][image] = '{"id":"041jd.jpg","storage":"cache","metadata":{...}}'
# ...
```

Then in your controller you would just pass these parameters when creating/updating the Album:

```rb
Album.create(params[:album])
```

The `:photos_attributes` attribute is generated from `Album.accepts_nested_attributes_for :photos`, and works as described in the ActiveRecord documentation. It doesn't matter whether the `image` is a Shrine attachment attribute or just a regular column attribute, it's all the same.

> How to validate presence of has_many :images on parent model.

See the ActiveRecord documentation on how to validate presence of associated records, this is not related to Shrine.

**Comment by devkir** [comment]
I tried on my controller `params.require(:parent_model).permit(photos_attributes: [:id, :image]` - it didn't work, validation also didn't worked. 
_Maybe it is because Photo model is polymorphic?_

**Comment by janko-m** [comment]
There could be a number of reasons why this didn't work. My guess is that you have to use `images_attributes` attribute, not `photos_attributes`, as you said you have `has_many :images`.

I would suggest you try to isolate your example in a script to prove that it works, and then debug why it doesn't work in your app. Here is my example proving that it works:

```rb
require "active_record"
require "shrine"
require "shrine/storage/file_system"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
  create_table(:albums)
  create_table(:photos) do |t|
    t.belongs_to :album
    t.string :image_data
  end
end

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir),
}

Shrine.plugin :activerecord

class ImageUploader < Shrine
  plugin :validation_helpers

  Attacher.validate do
    validate_min_size 1
  end
end

class Album < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos
  validates_presence_of :photos
end

class Photo < ActiveRecord::Base
  include ImageUploader::Attachment.new(:image)
end

#===================

album = Album.new(photos_attributes: {
  '0' => { image: StringIO.new("file") }
})

album.save # => true
album # => #<Album id: 1>
album.photos.to_a # => [#<Photo id: 1, album_id: 1, image_data: "{\"id\":\"f7e802388a50aa872534b93de2e17039\",\"storage\"...">]

#===================

album = Album.new(photos_attributes: {
  '0' => { image: StringIO.new("") }
})

album.save # => false
album.valid? # => false
album.errors.to_h # => {:"photos.image"=>"is too small (min is 0 MB)"}

#===================

album = Album.new(photos_attributes: {})

album.save # => false
album.valid? # => false
album.errors.to_h # => {:photos=>"can't be blank"}
```

I will close this ticket, as there doesn't appear to be any bug with Shrine.
