### ISSUE TITLE
Error determining mine type

### ISSUE THREAD

**Issue by masonjm** [shrinerb/shrine#279]
### Brief Description
I'm seeing an `undefined method` error occasionally when processing files. I'm not sure what triggers the error, but it's possible we're trying to upload a file that doesn't exist (timing issues).

```
undefined method `success?' for nil:NilClass
["/emf/spotdir/shared/bundle/ruby/2.3.0/gems/shrine-2.9.0/lib/shrine/plugins/determine_mime_type.rb:170:in `block in extract_with_file'",
 "/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:205:in `popen_run'", 
 "/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:95:in `popen3'", 
 "/emf/spotdir/shared/bundle/ruby/2.3.0/gems/shrine-2.9.0/lib/shrine/plugins/determine_mime_type.rb:161:in `extract_with_file'", 
 "/emf/spotdir/shared/bundle/ruby/2.3.0/gems/shrine-2.9.0/lib/shrine/plugins/determine_mime_type.rb:150:in `call'"]
```

### Expected behavior
A more graceful failure. Probably just testing for `thread.value` being `nil`.

### Actual behavior
Stack trace :(

### System configuration
**Ruby version**:
2.3.1

**Shrine version**:
2.9.0

**Comment by hmistry** [comment]
Thanks for reporting this. I'll create a PR for it but it'll most likely end up in master and in the next release which means you'll have to update Shrine once it's released to get the changes.

**Comment by masonjm** [comment]
Sounds perfect. Thank you!

**Comment by janko-m** [comment]
Thanks for reporting!

The `thread` here is the result of `Process.detach`, and its documentation states:

> The waiting thread returns the exit status of the detached process when it terminates, so you can use Thread#join to know the result.  **If specified pid is not a valid child process ID, the thread returns nil immediately.**

So it seems that, although `pid = spawn("...")` and `Process.detach(pid)` happen in adjacent lines in the Open3 stdlib (used by the determine_mime_type plugin), the `pid` could still somehow not be a valid child process ID. That baffles me a bit. I tried providing empty files, but I couldn't reproduce the issue.

I will try to research more on when it could happen, but I'll gladly merge @hmistry's PR in the meanwhile.

**Comment by janko-m** [comment]
We haven't yet determined what causes the child process to fail to spawn, but at least now an explicit `Shrine::Error` will be raised with stderr included in the message.
