### ISSUE TITLE
Complicated shrine.rb

### ISSUE THREAD

**Issue by printercu** [shrinerb/shrine#316]
Hi!

`lib/shrine.rb` is quite complicated now and contains source for storage, attachment, plugins, etc. altogether.

WDYT about extracting UploadedFile, Attachment and others to `lib/shrine/uploaded_file.rb`, `lib/shrine/attachment.rb` and move code from Plugins::Base::AttachmentMethods and similar to this new files? I can perform this.

**Comment by janko-m** [comment]
I agree that it would be beneficial to split `lib/shrine.rb` in the way that you described, that would definitely make it easier for users to read the code. Feel free to make the PR, thank you!
