### ISSUE TITLE
Surprising behavior when a param is ActionController::Parameters instead of a JSON string

### ISSUE THREAD

**Issue by ndbroadbent** [shrinerb/shrine#335]
I believe this is might be a bug, but sorry if this is more suitable for the mailing list.

### Brief Description

I'm writing a test that sets up some cached file data, and sends a request to the `#update` action on a controller, which should update the file attachment on a model.

This has been working fine in development, but I was struggling to get this to work in my test. I inspected the params that were working in development, and was surprised to see that it was a plain string with encoded JSON data:

```ruby
{
    "document" => "{\"id\":\"1161f860df090f95533b78c0e5b117c0.pdf\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"test_file.pdf\",\"size\":5885,\"mime_type\":\"application/pdf\",\"md5_hash\":\"3c957f2c43dfffa582f80fe1d79ef7a8\"}}"
}
```

This is working fine in development. Shrine will parse the JSON string, and then promote the file from `cache` to `store`.

I am writing a test for a new JSON API endpoint. So I was passing this param as a plain JSON object, and the param looked like this:

```ruby
{
    "document" => {
              "id" => "b6903dbfb15c13bbad1444c35064df9e",
         "storage" => "cache",
        "metadata" => {
                 "size" => 5885,
             "filename" => "test_file.pdf",
            "mime_type" => "application/pdf"
        }
    }
}
```

When I called: `model.update(document: params[:document])`, Shrine crashed with a `Shrine::InvalidFile` error:

```
        Shrine::InvalidFile:
            "b6903dbfb15c13bbad1444c35064df9e" is not a valid IO object (it doesn't respond to #read, #eof?, #rewind, #close)
          # /Users/ndbroadbent/.rvm/gems/ruby-2.5.3/bundler/gems/shrine-b760219c0c70/lib/shrine.rb:370:in `_enforce_io'
          # /Users/ndbroadbent/.rvm/gems/ruby-2.5.3/bundler/gems/shrine-b760219c0c70/lib/shrine.rb:301:in `_store'
```

This was really surprising. In my API documentation, I don't want to tell people that they should encode this document data into a string, because that would be weird. So I ended up doing that in my controller:

```ruby

def model_params
  params.require(:model).permit(
    :document,
  ).tap do |permitted|
    unless permitted[:document]
      permitted[:document] = params[:model][:document]
    end

    # document can be one of:
    # * String (presigned upload from web UI, JSON-encoded)
    # * ActionController::Parameters (presigned upload from API request)
    # * Rack::Multipart::UploadedFile (form post)
    if permitted[:document].is_a?(ActionController::Parameters)
      permitted[:document] = permitted[:document].permit!.to_json
    end
  end
end
```

This basically converts the Hash into a JSON encoded string, so that Shrine can decode the JSON back into a Hash again.

I'm just wondering if this is necessary, or if Shrine could just accept the Hash instead of a String with JSON data?

### System configuration
**Ruby version**: 2.5.3

**Shrine version**: 2.8.0

**Comment by jrochkind** [comment]
The reason it accepts the string, is because that is very convenient for sending back the params in a single hidden form field, from a form submission. 

parsed_json plugin should make it also accept a hash. Personally, I have wondered if it should just do this by default, without the plugin -- I always load the plugin myself, just to avoid confusion.

**Comment by ndbroadbent** [comment]
Oh I see, it looks like the `parsed_json` plugin is [just doing the same thing](https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/parsed_json.rb#L14) as my `model_params` method (calling `.to_json` on the Hash). 

In that case I might just keep doing it in the controller for now, so at least it's explicit about what Shrine accepts. It feels like an ugly workaround though.

Is this related to [the `#uploaded_file` method in Shrine](https://github.com/shrinerb/shrine/blob/master/lib/shrine.rb#L116-L127)?

If so, it looks like this calls itself recursively until it ends up with an instance of `UploadedFile`, so I'm not sure why it wouldn't be working for a plain Hash. (But I'm probably looking at the wrong code.)

**Comment by jrochkind** [comment]
If you would have expected it to Just Work... why not add the plugin so it does? I'm curious your reluctance -- do you still think we should make shrine accept Hash's by default out of the box? (I lean towards thinking so, but haven't thought it all through as much as @janko-m so there may be reasons for it not to).

**Comment by ndbroadbent** [comment]
> If you would have expected it to Just Work... why not add the plugin so it does?

Yeah I might do that, but the plugin just feels like a strange workaround. It converts the Hash into JSON, and then Shrine deserializes it back into a Hash.

> do you still think we should make shrine accept Hash's by default out of the box?

I think that would make sense as a default.

I'm not sure about using the `uploaded_file` method, but if it's not already being used during deserialization then I think that would make sense. 

I just think it would better to handle this case, instead of throwing a `Shrine::InvalidFile` error because the "id" string doesn't respond to IO methods

**Comment by janko-m** [comment]
I think the main reason why I made it a plugin was because the attachment setter method (`Attacher#assign`) also accepts a hash of files when the `versions` plugin is loaded, e.g.

```rb
model.document = { cover: File.open("..."), content: File.open("...") }
```

With that and with `parsed_json` functionality being in the core there would be too many possible types of input:

* raw file
* uploaded file JSON
* uploaded file Hash
* hash of raw files
* hash of uploaded file JSONs

Because I felt like having so many possibilities could cause some problems, I decided to extract it into a plugin, so that if it causes a problem for some people then they can not load the plugin and convert to JSON instead.

That wasn't the right thinking, however. The real problem was the `versions` plugin enabling you to assign a hash of versions. In https://github.com/shrinerb/shrine/pull/299 we are working on a rewrite of the `versions` plugin (which will be called `derivatives`/`derivates`), where you would be able to assign any "versions" via a separate API.

After that is in place and assigning a hash of versions functionality is removed in Shrine 3 (though the `versions` plugin would probably still be supported in Shrine 3), it would make sense to support assigning an uploaded file as a Hash by default.

**Comment by ndbroadbent** [comment]
Thanks, that makes sense! I can see how the different possibilities could cause some issues. 

#299 sounds like it could be a good solution. Will keep an eye on that and try it out when it's ready.

Maybe there could also be a new `versions` plugin that adds some top-level keys to differentiate between single files and versions:

* **raw file**

```ruby
model.document = { file: File.open("...") }
```

* **uploaded file JSON**

```ruby
model.document = { file: "{ \"id\": \"1234567890\", \"store\": \"cache\" }" }
```

* **uploaded file Hash**

```ruby
model.document = { file: { "id": "1234567890", "store": "cache" } }
```

* **versions: raw files**

```ruby
model.document = { versions: { cover: File.open("..."), content: File.open("...") } }
```

* **versions: uploaded file JSONs**

```ruby
model.document = { versions: { cover: "{ ... }", content: "{ ... }" } }
```

It would be good if it only supported those two top-level keys (`:file` and `:versions`), and crashed with an error if they aren't present, or if any other keys are present. Then you can still accept File/Hash/String, but it's a bit more explicit.

Anyway, just an idea! Look forward to trying out #299 when it's ready, and also Shrine 3. Thanks for all your work!

**Comment by ndbroadbent** [comment]
@janko I'm trying to upgrade to `3.0.0.rc`, and I can see that the `parsed_json` plugin has now been removed. I just wanted to ask if anything has changed, and what I should be doing now for this issue? Thanks!

**Comment by janko** [comment]
The `parsed_json` plugin has been removed because it's now the default behaviour. I see that it wasn't clear from the release notes and upgrading guide, I'll try to improve that.
