### ISSUE TITLE
Temp files deleted before upload

### ISSUE THREAD

**Issue by mcelicalderon** [shrinerb/shrine#338]
### Brief Description
When doing some custom processing to add versions in an uploaded file, I get a file not found error if one of the versions takes too long to upload

### Expected behavior
Should be able to upload as many versions as necessary without some of the temfile versions being deleted before they are uploaded

### Actual behavior
If the first version that is uploaded takes a bit longer than usual (more than 1 sec) the remaining versions will fail to upload as they have been removed from the temp file directory.

### Shrine config file
```ruby
require 'shrine/storage/file_system'
require 'shrine/storage/s3'

Shrine.storages = if Rails.env.test?
  {
    cache: Shrine::Storage::FileSystem.new('tmp', prefix: 'uploads/cache'),
    store: Shrine::Storage::FileSystem.new('tmp', prefix: 'uploads')
  }
else
  aws_secrets = Rails.application.secrets.aws

  {
    cache: Shrine::Storage::FileSystem.new('tmp', prefix: 'uploads/cache'),
    store: Shrine::Storage::S3.new(
      prefix:            Rails.env,
      bucket:            aws_secrets[:bucket],
      access_key_id:     aws_secrets[:access_key_id],
      secret_access_key: aws_secrets[:secret_access_key],
      region:            aws_secrets[:region]
    )
  }
end

Shrine.plugin :activerecord
Shrine.plugin :delete_promoted
Shrine.plugin :remove_invalid
Shrine.plugin :determine_mime_type
Shrine.plugin :infer_extension
Shrine.plugin :processing
Shrine.plugin :versions
Shrine.plugin :copy
Shrine.plugin :remote_url, max_size: 50 * 1024 * 1024
Shrine.plugin :validation_helpers, default_messages: {
  max_size:            ->(max) { I18n.t('errors.file.max_size', max_size: max) },
  mime_type_inclusion: ->(whitelist) { I18n.t('errors.file.mime_type_inclusion', whitelist: whitelist) }
}
```

### Simplest self-contained example code to demonstrate issue
```ruby
process(:store) do |io, _context|
    io.download do |download|
        pipeline = ImageProcessing::MiniMagick.source(download).convert('jpg')

        thumbnail = pipeline.resize_to_limit!(1000, 1000)

        { original: io, thumbnail: thumbnail }
    end
end
```

### Backtrace
```
No such file or directory @ rb_file_s_size - /tmp/20181219-1-1r3p9az20181219-1-jef5uh
----------
/GEM_ROOT/gems/aws-sdk-s3-1.30.0/lib/aws-sdk-s3/file_uploader.rb:31→ size
--
/GEM_ROOT/gems/aws-sdk-s3-1.30.0/lib/aws-sdk-s3/file_uploader.rb:31→ upload
/GEM_ROOT/gems/aws-sdk-s3-1.30.0/lib/aws-sdk-s3/customizations/object.rb:308→ upload_file
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/storage/s3.rb:478→ put
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/storage/s3.rb:301→ upload
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:348→ copy
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:337→ put
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:321→ _store
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/plugins/versions.rb:233→ _store
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/plugins/versions.rb:228→ block in _store
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/plugins/versions.rb:227→ each
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/plugins/versions.rb:227→ inject
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/plugins/versions.rb:227→ _store
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:248→ store
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:226→ upload
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:658→ store!
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:588→ promote
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/plugins/delete_promoted.rb:14→ promote
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:582→ _promote
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine.rb:577→ finalize
/GEM_ROOT/gems/shrine-2.13.0/lib/shrine/plugins/activerecord.rb:113→ block in included
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426→ instance_exec
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426→ block in make_lambda
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:261→ block in conditional
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:517→ block in invoke_after
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:517→ each
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:517→ invoke_after
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:133→ run_callbacks
/GEM_ROOT/gems/airbrake-7.4.0/lib/airbrake/rails/active_record.rb:25→ run_callbacks
/GEM_ROOT/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:816→ _run_commit_callbacks
/GEM_ROOT/gems/activerecord-5.2.2/lib/active_record/transactions.rb:346→ committed!
```

### System configuration
**Ruby version**: 2.5.3

**Shrine version**: 2.13.0

### Notes
Following the stack trace, looks like the code might be loosing the reference to the tempfile as only the path (string) is used on the upload. If no reference is kept from the tempfile might be the reason why it gets deleted. Changing the code to upload the smaller file first `{ thumbnail: thumbnail, original: io }` fixes it every time. But probably would still fail if uploading more versions.

Let me know if I can provide additional information on this.
Thanks

**Comment by janko-m** [comment]
Thank you for the report. This is very worrisome, I don't see a reasonable explanation on why this is happening.

> Following the stack trace, looks like the code might be loosing the reference to the tempfile as only the path (string) is used on the upload. If no reference is kept from the tempfile might be the reason why it gets deleted.

Yes, Tempfiles will get deleted by the garbage collector once the reference to the Tempfile instance is lost and the GC starts. However, this is not the case here. Yes, in the `S3#upload` method we are calling `Aws::S3::Object#upload_file` with only the tempfile path, but after that method call we might still use the Tempfile instance in `S3#upload`, Ruby doesn't know.

Even if Ruby somehow detects that we're not using the Tempfile object anymore for the remainder of that method, we're still using it in `Shrine#copy` after we've called `S3#upload`, where we `#close` the Tempfile.

Maybe the `delete_promoted` plugin is somehow causing issues, can you try removing it? I'll try to reproduce this at some point, but if you can it would be very helpful if you could come up with a single Ruby script that I can execute and will cause the bug, that would greatly speed up resolving this issue (a template for such a script is in `CONTRIBUTING.md`).

**Comment by mcelicalderon** [comment]
Sure, will try to replicate in that format as soon as possible. Thanks

**Comment by mcelicalderon** [comment]
Closing this one as it looks like the problem was in another gem I'm using [ImageOptim](https://github.com/toy/image_optim). It seems that maybe they are not handling the tempfile reference correctly, in a way the file is not removed. Will keep looking into it, thanks for the response.

**Comment by mcelicalderon** [comment]
So yes, this was not a problem with Shrine after many tests. In the end it was actually a problem with how the ImageOptim gem returns results. Just posting this here as there is an example on how to use the ImageOptim gem on the versions plugin readme [here](https://github.com/shrinerb/shrine/blob/a0e4fa856e5782e7cc186c26ccf8cf37764accda/doc/processing.md).

So if it helps anyone, the only solution I have found so far is to create my own Tempfile and write the contents of the optimized file, close and reopen (closing actually writes all info to disk, useful if inferring the file type with plugin), and the passing the new tempfile as one of the versions hash. Not sure if there is a better way, maybe allow shrine to receive a path type object and open internally? That way the reference to the image optim optimized path would be kept so the internal tempfile is not deleted. Might be useful for integrations with other gems that work in the same way.

**Comment by janko-m** [comment]
Interesting, thanks for pointing out your findings. From my code readings it seems that

```rb
ImageOptim.new.optimize_image(original.path)
```

will return a temporary path on disk created by the `tempfile` stdlib. This is very bad, because if you have only the path, that means you lost reference to the `Tempfile` object, and the garbage collector might delete the file before you're finished using it (which seems to be your case). Having only the path is not enough to prevent that, from what I've experienced.

What you described sounds good. I don't know if you're using it, but I think using `#optimize_image!` is the safest, because it would prevent ImageOptim from creating a new temporary path altogether. For example, you could then modify the original image:

```rb
image = io.download

image_optim = ImageOptim.new
image_optim.optimize_image!(image.path)
image.open # refresh file descriptor

image
```

Does that approach look good to you? If yes, we could update the Shrine documentation to show the safe usage of ImageOptim instead.

P.S. Man, the ImageOptim gem source code is really complex. There are so many things other than image optimization going on under the hood (filesystem stuff), and I've even seen some "workers", definitely feels like too much.

**Comment by mcelicalderon** [comment]
Yes, I think that would be a good change for the docs. Sadly it won't work for my scenario where I want to create multiple versions of the same original image. But looks like I might have to do it myself as there are no good gems that handle new file output properly.

And yes, image optim's code does look way too complex. Might go with a fork for a simpler gem like [Piet](https://github.com/albertbellonch/piet) that is not perfect but will be easier to change and does much less.

Thank you for looking into this.

**Comment by janko-m** [comment]
Ok, thanks for the heads up, I would like the docs to show a generic example. This looks like it would work for your use case:

```rb
process(:store) do |io, context|
  optimized = Tempfile.new(["optimized", "#{io.extension}"], binmode: true)

  io.download do |original|
    IO.copy_stream(original, optimized.path)
    original.rewind

    image_optim = ImageOptim.new
    image_optim.optimize_image!(optimized.path)
    optimized.open # refresh file descriptor
  end

  optimized
end
```

**Comment by mcelicalderon** [comment]
That is perfect! I'm sure that will work for my use case and the same approach can be used for others, so that would be the perfect example on the docs. Thanks a lot! I feel like this thread should go in ImageOptim's repo as it's mostly an issue with their gem, but I'm glad you could find a workaround.
