### ISSUE TITLE
Unable to access stored file in the after_upload hook

### ISSUE THREAD

**Issue by bodrovis** [shrinerb/shrine#340]
### Brief Description
Hello again! Recently we experienced some weird stuff like files not being saved to S3 for some reason, and so decided to add a small check to see if the file was actually stored or not. Basically, we check whether the file is present on S3 and if not - ask the user to try again.

I decided to utilize hooks https://shrinerb.com/rdoc/classes/Shrine/Plugins/Hooks.html specifically `after_upload`. However, the problem is I can't access the stored file from inside the hook. When I access the `context[:phase]` it says `:store` but the record's attachment has only `cache` storage at this point:

```
[5] pry(#<DocumentUploader>)> context[:record].document
=> #<DocumentUploader::UploadedFile:0x0000000016508fa0
 @data=
  {"id"=>"0ca86c442b9859e339c71f38fa8ce121.doc",
   "storage"=>"cache",
   "metadata"=>
    {"filename"=>"mindflow5_27-29.doc", "size"=>457216, "mime_type"=>"application/msword"}}>
```

Then, *after* this hook I can see that my record is being updated with a `store` storage:

```
 SampleDraft Update (0.5ms)  UPDATE "sample_drafts" SET "document_data" = $1, "updated_at" = $2 WHERE "sample_drafts"."id" = $3  [["document_data", "{\"id\":\"f117168e930148f01a99c78928381fde.doc\",\"storage\":\"store\",\"metadata\":{\"filename\":\"mindflow5_27-29.doc\",\"size\":457216,\"mime_type\":\"application/msword\"}}"], ["updated_at", "2019-01-15 16:02:12.679998"], ["id", 12]]
```

### Expected behavior
For the `after_upload` hook I am expecting to get access to the file under the `store` storage, not `cache`. I mean, if this is "after upload", then the file should be already uploaded.

### Actual behavior
I can only get access to `cache` storage and, consequently, to the cached version of the file. There is no way to hook into the point where the file was stored in the `store`.

### Simplest self-contained example code to demonstrate issue
```ruby
class DocumentUploader < Shrine
  plugin :hooks

  def after_upload(io, context)
    super
    binding.pry # <= stop code execution right here for debugging
  end
end
```

### System configuration
**Ruby version**:
2.4.4
**Shrine version**:
2.14.0
**Rails version**:
5.2.2

**Comment by janko-m** [comment]
@bodrovis The `#after_upload` hook doesn't have access to the uploaded file, because the `Shrine::UploadedFile` instance is not saved anywhere (Shrine uploaders don't mutate their state). The `io` argument will still be the raw file that was uploaded, so there is no other state to retrieve.

However, you can use the `#around_upload` hook to get the result:

```rb
  def around_upload(io, context)
    uploaded_file = super
    uploaded_file #=> #<Shrine::UploadedFile>
  end
```

**Comment by bodrovis** [comment]
Oh, that explains it. Thank you! Perhaps, it should be  mentioned somewhere in the docs :)
