### ISSUE TITLE
AWS S3 'SignatureDoesNotMatch' with certain filenames

### ISSUE THREAD

**Issue by TrevorHinesley** [shrinerb/shrine#355]
### Brief Description
A user reported that some files were stuck in processing, which meant our promote job wasn't completing. Each time his files retry in Sidekiq, they fail with a `SignatureDoesNotMatch` error in S3, but uploading works fine otherwise. After diagnosing, it turns out it's due to the filenames.

### Expected behavior
The files should upload just fine (other files do, and there's nothing special about these other than the filename).

### Actual behavior
A certain subset of uploads are stuck in retries in Sidekiq, and keeps showing `Aws::S3::Errors::SignatureDoesNotMatch (The request signature we calculated does not match the signature you provided. Check your key and signing method.)`. Changing the filename and reuploading worked. Using the same file names causes the same problem again, so it's replicable.

### Simplest self-contained example code to demonstrate issue
Exact filenames that cause this issue: `19 Room Far  - .wav`, `02 Kick 88  - .wav`, etc.

### System configuration
**Ruby version**: 2.5.1

**Shrine version**: 2.12.0

**Comment by TrevorHinesley** [comment]
I'm wondering if this is due to this line:

https://github.com/shrinerb/shrine/blob/master/lib/shrine/storage/s3.rb#L107

In the case of one of the examples above, the `ContentDisposition.inline(filename)` would return:

`"inline; filename=\"02 Kick 88  - .wav\"; filename*=UTF-8''02%20Kick%2088%20%20-%20.wav"`

Is it possible that this isn't matching what's signed? This header has caused issues before if it doesn't match (i.e. https://github.com/aws/aws-sdk-js/issues/1648).

**Comment by janko** [comment]
I think you are using a Shrine version that doesn’t yet use the ContentDisposition gem. Could you try updating to the latest version?

**Comment by TrevorHinesley** [comment]
I'll give it a go and report back ASAP!

**Comment by TrevorHinesley** [comment]
Ahh so interestingly, only one of the many that were failing is failing now. And here's the difference.

Works: `02 Kick 88 - .wav`

Fails: `19 Room Far  - .wav`

The second, with two spaces before the `-`, fails.

**Comment by janko** [comment]
I tried reproducing using `aws-sdk-s3` directly, but the upload succeeds with both filenames:

```rb
require "aws-sdk-s3"
require "content_disposition"

resource = Aws::S3::Resource.new(
  region:            "...",
  access_key_id:     "...",
  secret_access_key: "...",
)

bucket = resource.bucket("...")
object = bucket.object("foo")

filename = "19 Room Far  - .wav"

object.put(
  body:                "content",
  content_disposition: ContentDisposition.inline(filename),
)
```

Could you post a self-contained example like the above which reproduces the failure?

**Comment by TrevorHinesley** [comment]
```
require "aws-sdk-s3"
require "content_disposition"

resource = Aws::S3::Resource.new(
  endpoint: "https://s3.wasabisys.com",
  access_key_id: "...",
  secret_access_key: "...",
  region: "us-east-1",
)

bucket = resource.bucket("my-bucket")
object = bucket.object("foo")

filename = "19 Room Far  - .wav"

object.put(
  body:                "content",
  content_disposition: ContentDisposition.inline(filename),
)
```
This produces the error for me.

We're using Wasabi, which is 100% bit-accurate with S3 and works great with AWS S3 SDK (they recommend using AWS SDK S3 actually. I'm going to try this with an actual S3 bucket to test as well.

**Comment by TrevorHinesley** [comment]
That's the problem, it's a Wasabi issue. Sorry for the headache, this works using a regular S3 endpoint.

**Comment by aperture147** [comment]
Thanks for your clarification on this problem, it's a problem on the Wasabi side, not S3 API or AWS SDK. No forum or documentation of Wasabi has officially mentioned this issue. It's 2025 now and people are still suffering from this stupid ancient bug. I've been smashing my head for quite a long time for this.
