### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_file_s_mtime 

### ISSUE THREAD

**Issue by speedo-spin** [shrinerb/shrine#358]
shrine.rb
```
require 'shrine'
require 'shrine/storage/file_system'

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new('public', prefix: 'uploads/cache'), # temporary
  store: Shrine::Storage::FileSystem.new('public', prefix: 'uploads'),       # permanent
}

Shrine.plugin :activerecord
Shrine.plugin :determine_mime_type
Shrine.plugin :cached_attachment_data # for retaining the cached file across form redisplays
Shrine.plugin :restore_cached_data # re-extract metadata when attaching a cached file
```
uploader
```
class Uploaders::Image < Shrine
  plugin :moving # move from cache
  plugin :pretty_location # generates location
  plugin :remove_attachment # allows to delete attachments through checkboxes on the web form
  plugin :store_dimensions, analyzer: :ruby_vips

  # validation
  plugin :validation_helpers
  plugin :remove_invalid


  plugin :derivation_endpoint,
         secret_key: App.config[:secret_key_base],
         upload: true,
         prefix: "derivations/image"

  derivation :small do |file, width = 300, height = 300|
    ImageProcessing::Vips
      .source(file)
      .saver(quality: 98)
      .resize_to_limit!(width.to_i, height.to_i, crop: :centre)
  end

  Attacher.validate do
    validate_max_size 5 * 1024 * 1024, message: "is too large (max is 5 MB)"
    validate_mime_type_inclusion %w[image/jpeg image/png image/jpg]
    validate_extension_inclusion %w[jpg jpeg png]
    validate_min_width 300
    validate_min_height 300
  end
end
```

routes:
```
  mount Uploaders::Image.derivation_endpoint => "derivations/image"
```
logs:
```
Started GET "/derivations/image/small/eyJpZCI6Im1vZGVyYXRvci8yL2F2YXRhci9lYmMyNTQ4NTEyYzlkMjAxNjRiMjIzMWVhMjAxMDliZS5qcGciLCJzdG9yYWdlIjoic3RvcmUifQ?signature=58eda4d98f6ebcb70c201da87b5976bf1976cfc1427ab30cf789d125ae632569" for 127.0.0.1 at 2019-03-02 19:30:37 +0300
  
Errno::ENOENT (No such file or directory @ rb_file_s_mtime - /tmp/image_processing20190302-18995-1pwwikb.jpg):
  
rack (2.0.6) lib/rack/file.rb:63:in `mtime'
rack (2.0.6) lib/rack/file.rb:63:in `serving'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:516:in `rack_file_response'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:448:in `file_response'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:497:in `upload_response'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:430:in `call'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:137:in `response'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:371:in `handle_request'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:335:in `block in call'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:332:in `catch'
shrine (2.16.0) lib/shrine/plugins/derivation_endpoint.rb:332:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.0.beta2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.0.beta2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.beta2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.beta2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.beta2) lib/action_dispatch/routing/route_set.rb:839:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/cookies.rb:644:in `call'
activerecord (6.0.0.beta2) lib/active_record/migration.rb:560:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.beta2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/debug_exceptions.rb:30:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0.beta2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.beta2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.beta2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.beta2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.beta2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.beta2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0.beta2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.beta2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
railties (6.0.0.beta2) lib/rails/engine.rb:523:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
DEPRECATION WARNING: ActionView::Base instances should be constructed with a lookup context,
assignments, and a controller.
 (called from new at /home/speedo/.rvm/gems/ruby-2.6.1@rails6/gems/web-console-3.7.0/lib/web_console/template.rb:21)
```

in html
```
current_user.avatar.derivation_url(:small)
```

file structure:
https://i.imgur.com/lmUUfzL.png

the error appears if :small version was not generated previously
after page refresh it works ok

When I remove small file version (or during new image upload):
expected result - derivation_endpoint should process the image and return small version on the fly
actual result - derivation_endpoint processed the file (I see resized image file in the directory), but in the response I got the error above, after page refresh response is ok (I see image in html)

if I remove  `upload: true` option from   plugin :derivation_endpoint, it also works ok

ruby 2.6.1
rails 6 beta2

**Comment by speedo-spin** [comment]
found out that `plugin :moving` caused the issue
so not sure if it's expected error or not


few more questions regarding derivation_endpoint
1. when I upload new file the previous `:small` versions are not deleted
https://i.imgur.com/3uNaiev.png
is there any option to delete old versions during new file upload?

2. `upload_redirect: true` does this option make sense only for non Shrine::Storage::FileSystem storages types, such as S3, etc ?

**Comment by hmistry** [comment]
Thanks for reporting the good write up with code samples.

I'll need to look into the `moving` plugin issue. I would not expect it to cause an issue.

1. You can use [`derivation.delete`](
https://github.com/shrinerb/shrine/blob/master/doc/plugins/derivation_endpoint.md#delete) to delete existing versions before updating the record with the new file.

2. Correct. The idea is to redirect the client to S3 to serve the file and not load your server with having to download the version from S3 and then serve it to the client. When you use the local file storage, you have no option but to serve the file from your server.

**Comment by janko** [comment]
> found out that plugin :moving caused the issue so not sure if it's expected error or not

Good catch. I've realized that `derivation_endpoint` is incompatible with the `moving` plugin as well, but it has slipped my radar. I've recently [fixed](https://github.com/shrinerb/shrine/commit/28308c0323cab6d04c307aab083c73d59956118c) the same problem with `delete_raw` plugin, the same kind of fix should work with `moving` plugin as well. @hmistry would you like to make a PR?

> when I upload new file the previous :small versions are not deleted
> is there any option to delete old versions during new file upload?

At the moment Shrine doesn't know which versions have you generated with which arguments, and where are they located (since you can change the `:upload_location`). Active Storage, on the other hand, uploads everything to a single `derivatives/<key>` directory (where `<key>` is the id of the source file), and on [`Blob#delete`](https://github.com/rails/rails/blob/f4a30d2a0706f278a20c63a3d99288de79b52e5f/activestorage/app/models/active_storage/blob.rb#L213-L216) it deletes variants automatically (using `#delete_prefixed`, which Active Storage services are required to implement).

As @hmistry said, you can currently do it manually via the Derivation API, e.g.

```rb
photo.image.derivation(:small).delete
```

It would be nice if we found a solution where uploaded derivatives were deleted automatically when the source file is deleted. Until then we should extend the docs with:

* mention about `Derivation#delete` in the "Uploading" section of the `derivation_endpoint` docs
* mention that `:upload_redirect` only makes sense for remote storage services

**Comment by hmistry** [comment]
@janko Sure I'll take care of the PR and docs.

**Comment by speedo-spin** [comment]
@janko @hmistry 
please check this one 
https://github.com/shrinerb/shrine/pull/359

**Comment by speedo-spin** [comment]
@janko @hmistry
```
At the moment Shrine doesn't know which versions have you generated with which arguments, and where are they located (since you can change the :upload_location)
```
maybe we can make it work out of the box with default settings
f.e. by using `pretty_location` and `derivation_endpoint` we have next structure by default
```
:model
  :id
    :attachment
      :uid
        :variation1-width-height      # variation 1
        :variation2-width2-height2  # variation 2
         ....
      :uid.:extension # original
```

You can see that by default all files that are related to specific attachment have the same uid in it's path.
So probably we can remove all files that is related to this uid when attachment_data is changed.

But of course if user modify `upload_location` path or `generate_location`, then it's up to user how to remove files.

Probably the general logic will be to look in path some specific match (uid in the example above) and remove if match is found.
Then we can provide such option (to find match) for deleting derivations on changes
what do you think?

**Comment by speedo-spin** [comment]
looks like https://github.com/shrinerb/shrine/pull/359 MR is merged, so I moved https://github.com/shrinerb/shrine/issues/358#issuecomment-468968147  question to google group
https://groups.google.com/forum/#!topic/ruby-shrine/2CgQJCh7TDs

**Comment by hmistry** [comment]
Deleting derivations on changes need some thought because Shrine works on plain ruby objects to Active Record, Sequel, and others so not all model objects will have a before update hook. It already stores the files in` <source id>/<name>-<args>` location so there might be a way to get it to purge that folder when the source file is changed. We would also need to consider race conditions.
