### ISSUE TITLE
Get original file name and versions plugin

### ISSUE THREAD

**Issue by shir** [shrinerb/shrine#364]
### Brief Description
I use the versions plugin for attachment.

I want to show the original file name on a page. For the processed file, I tried to use `file.original_filename` but got error
```
undefined method `original_filename' for #<Hash:0x00007fe57347a940>
```
And if I use `file[:original].original_filename` when it works as expected.

But when I use `file[:original].original_filename` on not processed file (background jobs after file upload were not run) I got other error:
```
undefined method `[]' for #<FileUploader::UploadedFile:0x00007fe5742b0820>
```
And  if I use `file.original_filename` in this case when it works as expected.

### Expected behavior
I expect to have the same way to access the original file name for processed and not processed files.

### Actual behavior
See above

### Simplest self-contained example code to demonstrate issue
```rb
require "active_record"
require "shrine"
require "shrine/storage/file_system"
require "tmpdir"
require "down"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(File.join(Dir.tmpdir, "shrine")),
  store: Shrine::Storage::FileSystem.new(File.join(Dir.tmpdir, "shrine")),
}

Shrine.plugin :activerecord

class MyUploader < Shrine
  plugin :processing
  plugin :versions

  process(:store) do |io, context|
    versions = { original: io } # retain original

   # Other versions generation

    versions # return the hash of processed files
  end
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }
# make errors propagate when raised in callbacks
ActiveRecord::Base.raise_in_transactional_callbacks = true

class Post < ActiveRecord::Base
  include MyUploader::Attachment.new(:image)
end

post = Post.create(image: Down.download("https://example.com/image-from-internet.jpg"))

post.image[:original].original_filename # <- This raises error on non processed file
post.image.original_filename # <- This raises error on processed file
```

### System configuration
**Ruby version**: 2.3.8

**Shrine version**: 2.16.0

**Comment by hmistry** [comment]
Thank you for clearly describing the issue and providing the test script.

Unfortunately what you are seeing is the correct behavior of the current implementation of versions plugin. It is not the ideal behavior, but at the time, it was the easiest way to implement versions plugin. We are working on a new versions plugin to address the inconsistent API between original and versions file attachments amongst other issues.

FYI, the reason you're seeing the above behavior is because the image data structure is changing between before and after processing. If you don't use the versions plugin or you do use it and before processing, the `post.image` data structure looks like this:

```ruby
{"id"=>"f316233",
 "storage"=>"store",
 "metadata"=>{"filename"=>"pic1.jpg", "size"=>11, "mime_type"=>nil}}
```

To access the filename, it is sufficient to use because internally we can map it correctly:

```ruby
post.image.original_filename
```

And after processing and storing versions (depends on the return hash of the process block), it will look like this:

```ruby
# example process block return value is
    process(:store) do |io, context|
      ...
      { original: io, small: small_image }
    end

# stored data in post.image
 {"original"=>
  {"id"=>"b46d61d",
   "storage"=>"store",
   "metadata"=>{"filename"=>"pic1.jpg", "size"=>11, "mime_type"=>nil}},
 "small"=>
  {"id"=>"2b58e48",
   "storage"=>"store",
   "metadata"=>
    {"filename"=>"shrine20190313-1dyrmsa.jpg",
     "size"=>11,
     "mime_type"=>nil}}}
```

To access the filename, you now need to pass a key to `image` to access the right version metadata because it can no longer predict the key for the original file if the user chose to keep it:

```ruby
post.image[:original].original_filename
```

I'm going to close this issue as we are working to fix this with the new versions plugin. Stay tuned.

**Comment by shir** [comment]
@hmistry could you reopen this issue or provide a link to other issue/PR where I can track progress and get a notification when it will be ready?

**Comment by hmistry** [comment]
I'll link it when I submit the PR.

**Comment by janko** [comment]
@shir One current workaround is using the `metadata_attributes` plugin to copy the filename to a separate column, e.g:

```rb
add_column :image_filename, :photos
```
```rb
class ImageUploader < Shrine
  plugin :metadata_attributes, filename: :filename
end
```
```
photo.image = file
photo.image_filename #=> "..."
photo.save
photo.image_filename #=> "..." (should stay the same)
```

**Comment by shir** [comment]
@janko thanks. I workaround by just defining a method on model level

```rb
  def original_filename
    if file.is_a?(Hash)
      file[:original]&.original_filename
    else
      file.original_filename
    end
  end
```

BTW, Does anybody know how I may override `original_filename` in uploader? Couldn't figure out it through the source.

**Comment by janko** [comment]
If you want to pass the filename in the controller, you can do it by using the `Attacher#assign` method explicitly:

```rb
photo.image_attacher.assign(file, metadata: { filename: "my filename" })
```

Alternatively, you can add the filename via Attacher context and use regular file assignment, then detect it in the uploader and assign it to the `filename` metadata key:

```rb
photo.image_attacher.context[:filename] = "my filename"
photo.image = file
```
```rb
class ImageUploader < Shrine
  plugin :add_metadata
  add_metadata do |io, context|
    { "filename" => context[:filename] }.compact
  end
end
```

Hopefully that helps. If not, we can continue on the Google group.

**Comment by ksol** [comment]
Regarding the original issue (ie. having an `UploadedFile` before processing and a `Hash` after), my workaround was to use a hash of versions as soon as possible, by adding:

```ruby
process(:cache) do |io, _|
  {original: io}
end
```

to my root uploader. I don't know yet if it's a good strategy, and I know it does not play well with all plugins (I had to make a custom versions of `ValidationsHelper`, for instance), but so far it seems worth it.

Hope this helps.

**Comment by janko** [comment]
The `versions` plugin rewrite is being tracked in https://github.com/shrinerb/shrine/issues/386.
