### ISSUE TITLE
File destroyed when version is string

### ISSUE THREAD

**Issue by molfar** [shrinerb/shrine#373]
I have spend all day catching this strange behaviour. I have simple processing, just like in docs. I generate versions of the file and have custom location. When I set versions name as String - whole file disappears from disk, it is removed by something. Just change version name to symbol - and It works fine, as expected. Here is short example code:

```
class SvgUploader < Shrine
  plugin :processing # allows hooking into promoting
  plugin :versions   # enable Shrine to handle a hash of files
  plugin :delete_raw # delete processed files after uploading
  plugin :delete_promoted
  plugin :validation_helpers
  plugin :determine_mime_type

  process(:store) do |io, context|
    versions = { original: io }

    io.download do |original|

      paint = Tempfile.new ['some', '.svg'], binmode: true
      # Some manipulating with xml code here
      paint.write doc.to_xml
      paint.open

      # versions['thumb'] = paint <<<---- DESTROYS all file after processing
      versions[:thumb] = paint # WORKS as expected
  end
  versions
end
```

Could you explain this case? I just have no idea. After saving record with version name as string - file is removed, but all data attribute looks right, and have proper file id. But file has gone from disk. I use dev local storage.

UPD

I think issue is here https://github.com/shrinerb/shrine/blob/ed75044de001a908dccb8111089eddba8ef742fd/lib/shrine/plugins/versions.rb#L75
When I changed it to 
`result.merge!(name.to_sym => _store(value, context.merge(version: name){|_, v1, v2| Array(v1) + Array(v2)}))`
It works. Also, this may need to be fixed in more places, then just this single line. Could you have a look at this String/Symbol workaround along whole versions plugin?

**Comment by janko** [comment]
Thanks for the report, I was able to reproduce the bug. Investigating now.
