### ISSUE TITLE
s3-accelerate returns Aws::S3::Errors::SignatureDoesNotMatch

### ISSUE THREAD

**Issue by masudhossain** [shrinerb/shrine#375]
### Brief Description
Been using AWS S3 normal version, and i recently upgraded to the s3-accelerate for faster upload. Uploading through a form works perfectly fine, but uploading using the `uploader = ImageUploader.new(:store)` way returns `Aws::S3::Errors::SignatureDoesNotMatch` error. If i disable s3-accelerate from my shrine.rb initializer, everything works fine from form upload to the backend upload.

Full code (`@video_id` is a random file i generate): 
http://prntscr.com/nagk6w
Shrine.rb setup: http://prntscr.com/nagl48

### Expected behavior
Should have uploaded to S3 using accelerate correctly.  

### Actual behavior
Returns this error: http://prntscr.com/nagkmj
`Aws::S3::Errors::SignatureDoesNotMatch`
`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

### Simplest self-contained example code to demonstrate issue
Provide a self-contained example code (see the [Sequel/ActiveRecord templates](https://github.com/shrinerb/shrine/blob/master/CONTRIBUTING.md)) to show the problem, and the full backtrace of any exception.
http://prntscr.com/nagkmj

### System configuration
**Ruby version**:
gem 'rails', '~> 5.0.2'
ruby 2.3.4p301
**Shrine version**:
shrine (2.12.0)

**Comment by janko** [comment]
It appears the correct way now to enable the accelerate endpoint is with `:use_accelerate_endpoint` (not `:endpoint`):

```rb
Shrine::Storage::S3.new(use_accelerate_endpoint: true, **other_options)
```

I'll update the docs.
