### ISSUE TITLE
demo README. I want a detail explanation of amazon S3

### ISSUE THREAD

**Issue by hide-furusawa** [shrinerb/shrine#377]
If do not have amazon S3, I want the explanation of procedure.
For example, use minio.
`https: // min.io /`

Here is how to use it.
to install
`brew install minio`

After installation. start minio
`minio server ~/minio/`

AccessKey and SecretKey is displayed in console log
Set below in env file.
`AccessKey: xxxxxxxxxxxxxxxxxx 
SecretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by hmistry** [comment]
Thank you for your request. The demo is merely a demo on how to use Shrine with a commonly used AWS Cloud Service as one example. We kept it simple otherwise it becomes a maintenance effort over time.

However with that said, would you like to make a PR with your changes?

**Comment by janko** [comment]
Minio is already mentioned elsewhere in Shrine guides, I don't think it needs to be mentioned in the demo README as well. The demo app is supposed to be just a simple example, it's proven to be enough of a maintenance burden as it is.
