### ISSUE TITLE
Processing blocks are shared between subclasses and parent

### ISSUE THREAD

**Issue by ksol** [shrinerb/shrine#379]
### Brief Description

When defining a processing block on an uploader subclass, it is also executed by the parent uploader.

### Expected behavior
I would expect that the subclass ends up with the parent processing block(s), or even with none; in any case, I was not expecting the parent class to run the process block defined by one of its subclass.

### Actual behavior
Assuming a situation like the following :
```ruby
class ImageProcessing < Shrine
  plugin :processing

  process(:store) { do_something }
end

class MoreSpecificImageProcessing < Shrine
  plugin :processing

  process(:store) { do_something_else }
end
```

Both class end up with the two processing block executed, meaning `ImageProcessing` will execute `do_something_else` too.

This happens wether the subclass specify `plugin :processing` or not, from my tests.

### Simplest self-contained example code to demonstrate issue

I managed to reproduce via a test case (to be put in `test/plugin/processing_test.rb`):

```ruby
it "doesn't share processing blocks" do
  @shrine.process(:foo) { |io, context| "something" }
  subclass = Class.new(@shrine)
  subclass.class_eval { plugin :processing}
  subclass.process(:foo) { |io, context| "something else" }

  refute_equal @shrine.opts[:processing], subclass.opts[:processing]
  assert_equal 1, @shrine.opts[:processing][:foo].size
  assert_equal 2, subclass.opts[:processing][:foo].size
end
```

I tried to fix it myself by changing `lib/shrine/plugins/processing.rb` and getting inspiration from #247, which looks similar, but somehow `opts[:processing][action]` always ends up shared.

### System configuration
**Ruby version**: 2.4 and 2.6 confirmed.
**Shrine version**: `master` as of writing.

Happy to provide more information if needed, or to do the actual PR if anyone has pointers on how to solve this.

In any case, thanks for a great lib !

**Comment by ksol** [comment]
I dug a little bit more, and my conclusion is that [these lines](https://github.com/shrinerb/shrine/blob/master/lib/shrine.rb#L51-L56) handle only one level of nested collection, while it should perform an actual `deep_dup`.

I ran a quick test using https://github.com/ollie/deep_dup, and it fixes the issue... while breaking the logger plugin, hehe.

I don't know what's the policy on introducing new dependencies, neither have I looked into fixing the logger plugin, please let me know what you think. In the meantime, I'll try and not mess with inheritance and uploaders.

**Comment by jrochkind** [comment]
Your diagnosis makes sense to me, and I agree this is a significant problem which oughta be fixed!

**Comment by janko** [comment]
Thanks for the report. An easy fix would be for the processing plugin to use the non-mutating `+=` when a new block is registered, instead of the mutating `<<`.

Feel free to send a pull request. Otherwise I should find time by the end of this week (I’m currently visiting my brother abroad and don’t have my laptop with me).

**Comment by ksol** [comment]
Yes indeed, it looks like it's working as I expect! I'll make something clean out of it and open a PR.

**Comment by janko** [comment]
Should be fixed in https://github.com/shrinerb/shrine/pull/380, thanks @ksol!
