### ISSUE TITLE
Passing custom location to new upload

### ISSUE THREAD

**Issue by devkir** [shrinerb/shrine#382]
Hello, thanks for awesome gem!
I want to make location + filenames to uploaded files using this structure: `storage_path/product_name/product_color__uid_generated_by_shrine.jpg`
Is it possible to set custom location to file when uploading files this way:
```
product = Product.find(product_id)
image = Image.new(product: product)
image.image_remote_url = url
image.save!
```

Or I have to use `generate_location(io, context)` method on my uploader, and get product attributes fetching Product by `product = Product.find(context[:record][:product_id])`?

### System configuration
**Ruby version**: 2.6.3

**Shrine version**: 2.16

**Comment by jrochkind** [comment]
I don't think you can do `image.image_remote_url=`.  I think you can override the `generate_location` method on your uploader though, which is maybe what you were suggesting?

When implementing the override, I _think_ you can access the current model with `context[:record]`, rather than having to fetch it again with a `Product.find`.

**Comment by devkir** [comment]
> I don't think you can do `image.image_remote_url=`. I think you can override the `generate_location` method on your uploader though, which is maybe what you were suggesting?
> 
> When implementing the override, I _think_ you can access the current model with `context[:record]`, rather than having to fetch it again with a `Product.find`.

I can't access product model from `context[:record]` it saves only the id of product.

I have done this by passing custom context:
`image.image_attacher.context[:custom_location] = "#{product.name}/#{product.color}"`
And then in ImageUploader:
```
def generate_location(io, context)
  if context[:version] == :thumbnail
    location = "thumbnails/#{super}"
  else
    location = "#{context[:custom_location]}_#{super}"
  end
  location
end
```

**Comment by janko** [comment]
It doesn't seem like you have to re-fetch the Product record, assuming ActiveRecord populates the association cache on `Image.new(product: product)`:

```rb
def generate_location(io, context)
  product = context[:record].product

  if context[:version] == :thumbnail
    "thumbnails/#{super}"
  else
    "#{product.name}/#{product.color}_#{super}"
  end
end
```

I've also just added the ability for `Attacher#assign_remote_url` to accept additional `Shrine#upload` options, so you can specify the location (though that applies only to temporary storage):

```rb
# ...
image.image_attacher.assign_remote_url(url, location: "...")
# ...
```

It's better the user the first approach, as that works for both temporary and permanent storage.

As this is a usage question and isn't showing any limitation in Shrine as far as I can tell, I'm closing this issue. In the future please ask usage questions on the `ruby-shrine` google group.
