### ISSUE TITLE
Upload Endpoint does not respond when uploading larger file sizes

### ISSUE THREAD

**Issue by paulbernhard** [shrinerb/shrine#383]
### Introduction
Following the [Direct App Uploads guide on Shrine's wiki](https://github.com/shrinerb/shrine/wiki/Adding-Direct-App-Uploads), i built a simple XHR uploader using Shrine's [Upload Endpoint](https://github.com/shrinerb/shrine/blob/v2.17.0/doc/plugins/upload_endpoint.md#readme) Plugin and [Uppy](https://uppy.io) for image and video uploads in a Ruby on Rails engine [Pshr](https://github.com/paulbernhard/pshr/). 

### Functionality
The engine mounts an upload endpoint to `/endpoint`, the engine is mounted by a main app at `/uploads`. Using Uppy with its [XHR Upload plugin](https://uppy.io/docs/xhr-upload/) in a form, a file is uploaded and followed by a post request to `/uploads/endpoint`. Shrine's upload endpoint responds witha JSON representation of the file, Uppy updates the form's file field, the form is submitted. 

File uploads will be processed later in the background (using Sidekiq).

### Actual behavior
Image uploads work well: the file is uploaded, the endpoint responds with its cache location (etc.), Uppy updates the file field on `upload-success`, the form is submitted, the record is saved and the file is being processed in the background.

When uploading video files of a bigger size (~ 34MB), the post request is made to the endpoint and nothing happens. After a while, nothing happens and Uppy responds with the message: _"Upload stalled for 30 seconds, aborting."_ I do not receive any other error message and smaller video uploads (~ 10MB) worked well.

Could it be that Shrine's upload endpoint has a problem with bigger file sizes?

### Code
routes:
```ruby
# engine routes
Pshr::Engine.routes.draw do
  mount Shrine.upload_endpoint(:cache) => 'endpoint'
end

# main app routes
Rails.application.routes.draw do
  # ...
  mount Pshr::Engine, at: "uploads"
  # ...
end
```

form:
```ruby
# _form.html.erb
<%= form_with model: upload, url: main_app.url_for(upload), local: false do |form| %>
  <%# ... %>
  <%= render 'pshr/uploads/fields', form: form %>
  <%= form.submit "Upload" %>
  <%# ... %>
<% end %>

# _fields.html.erb
<%= form.hidden_field :file, value: nil, data: { "target": "pshr--uploader.file" } %>
<div class="pshr-uploader__drop" data-target="pshr--uploader.drop">
  <%# ... %>
</div>
```

js:
```js
// uploader_controller.js
this.uppy = Uppy({
    autoProceed: true,
    allowMultipleUploads: true,
    restrictions: {
      maxNumberOfFiles: this.maxNumberOfFiles,
      allowedFileTypes: this.whitelist,
      maxFileSize: this.maxFileSize
    }
  })
  .use(DragDrop, {
    target: this.dropTarget
  })
  .use(XHRUpload, {
    endpoint: this.data.get('endpoint'),
    fieldName: 'file'
  })
  .use(Informer, {
    target: this.informerTarget
  })

this.uppy.on('upload', (data) => {
  this.uppy.info('')
})

this.uppy.on('upload-progress', (file, progress) => {
  // update progress bar...
})

this.uppy.on('upload-success', (file, response) => {
  this.fileTarget.value = JSON.stringify(response.body)
  this.progressTarget.innerHTML = `### Uploaded ${file.name} ###`
  // preview the file before submit ...
})

this.element.closest('form').addEventListener('submit', (event) => {
  // reset form after submit
})
}
```

### System configuration
'ruby' '2.6.1'
'shrine', '~> 2.16'

Thanks for everything!

**Comment by janko** [comment]
There was a problem with Rack's multipart parser where parsing large request bodies was CPU-intensive, but I think that happened with much larger files, and also newer versions of Rack have fixed that issue.

I planned to add `PUT` upload functionality to `upload_endpoint` at some point. With PUT uploads, request body = file content, so there is no multipart parsing. But I postponed that once Rack had fixed its issues.

So I don't know what could be causing this behaviour. Are you using filesystem or S3 storage? It would be very helpful if you could produce a minimal self-contained example which reproduces the problem, for example:

```rb
# script.rb
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "shrine", "~> 2.16"
  gem "rack", "~> 2.0"
  gem "rack-test_app"
end

require "rack"
require "shrine"
require "shrine/storage/file_system"

Shrine.storages[:cache] = Shrine::Storage::FileSystem.new(Dir.tmpdir)
Shrine.plugin :upload_endpoint

app = Rack::Builder.app do
  map "/upload" do
    run Shrine.upload_endpoint(:cache)
  end
end

tempfile = Tempfile.new
File.write(tempfile.path,  "a" * 34*1024*1024)

response = Rack::TestApp.wrap(app)
  .post("/upload", multipart: { "file" => File.open(tempfile.path) })

uploaded_file = Shrine.uploaded_file(response.body_json)
puts uploaded_file.size == 34*1024*1024
puts uploaded_file.read == "a" * 34*1024*1024
```
```
$ time ruby script.rb
The "mime_type" Shrine metadata field will be set from the "Content-Type" request header, which might not hold the actual MIME type of the file. It is recommended to load the determine_mime_type plugin which determines MIME type from file content.
true
true

real    0m1.458s
user    0m0.699s
sys     0m0.527s
```

**Comment by paulbernhard** [comment]
Thanks for your fast reply.

I am using filesystem storage and the error occurs in development on my local machine. I realised that the local Rails server spends quite some time on a "ffmpeg" process in my terminal (see [screenshot here](http://pbernhard.com/storage/screenshot_190513.png)). During the "ffmpeg" process the server is also kind of stuck and can't be stopped.

I also have the "streamio-ffmpeg" gem in my Gemfile and the same error occurs without the gem; although it's anyway only used for processing at a later stage.

I don't have the time for a self-contained example right now, but i will build one asap.

Thanks!

**Comment by paulbernhard** [comment]
Hi,

as i am going to have several video uploads, i gave the `Tus` protocol and the `shrine-tus` plugin a try, following the [Adding Resumable Uploads guide](https://github.com/shrinerb/shrine/wiki/Adding-Resumable-Uploads) closely. With this solution the direct uploads work for video as well. So i will run all my uploads via Tus. Thanks for all that great work!

I get this is no longer an "issue", but i still have two open questions regarding the uploading with `shrine-tus`.

### one

After uploading a file i want to display the cached version while to file is being processed in a background job which might take a while for larger videos. Using `Shrine::Storage::Tus.new` as cache storage now, i get a `RoutingError` for requesting files from cache, such as:

```bash
ActionController::RoutingError (No route matches [GET] "/uploads/cache/http:/localhost:3000/uploads/files/422f3e5cf25dc72322c470ebd0921779")
```

My shrine setup is…

```ruby
# config/initializers/shrine.rb
if Rails.env.test?
  Shrine.storages = {
    cache: Shrine::Storage::Memory.new,
    store: Shrine::Storage::Memory.new
  }
else
  Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new(Pshr.uploads_dir, prefix: Pshr.uploads_cache_prefix),
    store: Shrine::Storage::FileSystem.new(Pshr.uploads_dir, prefix: Pshr.uploads_store_prefix),
    tus:   Shrine::Storage::Tus.new
  }
end

Shrine.storages[:cache] = Shrine.storages[:tus]

# config/initializers/pshr.rb
# setup of my engine which uses Shrine
Pshr..uploads_dir = "public"
Pshr.uploads_cache_prefix = "uploads/cache"
Pshr.uploads_store_prefix = "uploads/store"
```

### two

Since i'm using the `Shrine::Storage::Tus` storage, i can't create uploads programatically. If i do…

```ruby
upload = Upload.new
upload.file = File.open(File.join(Rails.root, "path-to-file.jpg"))
```
… i am getting:

```bash
NoMethodError (undefined method `url' for #<File:0x00007fe7931b4a68>)
```

In the [Usage section of `shrine-tus`](https://github.com/shrinerb/shrine-tus#usage) you are mentioning the creation of a record like…

```ruby
file_data #=> {"id":"http://tus-server.org/68db42638388ae645ab747b36a837a79", "storage":"cache", "metadata":{...}}
Movie.create(video: file_data)
```

… and obviously i am missing out on something. Could you explain, how to create records programatically?

Thanks!

**Comment by janko** [comment]
> Using Shrine::Storage::Tus.new as cache storage now, i get a RoutingError for requesting files from cache

I'm not sure what's going on here. It seems that the storage prefix you've configured is somehow creeping into the URL. What is your data column showing? Are you getting that when calling Shrine's `#url` method?

I don't really have enough information to figure out what's going on, I only have your storage configuration which is the same as in the guide. Could I ask for a self-contained example that reproduces the unexpected behaviour (ideally without the `pshr` gem)?

> Since i'm using the Shrine::Storage::Tus storage, i can't create uploads programatically.

If I understand correctly, you want to upload a file to the tus server from Ruby (as opposed to on the client side)? I'm afraid that's not possible yet, as we'd need a `tus-ruby-client` library which speaks the tus protocol, and there isn't one yet. However, I have actually started work on it, I just haven't open-sourced it yet. But it's basically finished, I just wanted to wrap up one more feature and write the documentation.

If this is indeed the functionality you want, I could release `tus-ruby-client` in the next week and implement `Shrine::Storage::Tus#upload` with it. Currently it's calling `Shrine::Storage::Url#upload` from the `shrine-url` gem, which doesn't upload anywhere and calls `#url` on the given file – that's why you're getting the error.

However, could I ask what is your use case? Where is this file coming from?

**Comment by paulbernhard** [comment]
Hi Janko,

thanks for your great support, again.

### Regarding the `RoutingError` and my storage configuration…

The problem seems to have solved itself overnight. In my previous `shrine.rb` initializer i falsely defined `Shrine.storages[:cache] = Shrine.storages[:tus]` for all enviroments, including my test environment which should only use `Shrine::Storage::Memory`. For some reason, changing my storage configuration to …

```ruby
if Rails.env.test?
  Shrine.storages = {
    cache: Shrine::Storage::Memory.new,
    store: Shrine::Storage::Memory.new
  }
else
  Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new(Pshr.uploads_dir, prefix: "uploads/cache"),
    store: Shrine::Storage::FileSystem.new(Pshr.uploads_dir, prefix: "uploads"),
    tus:   Shrine::Storage::Tus.new
  }

  # use :tus storage as :cache storage
  Shrine.storages[:cache] = Shrine.storages[:tus]
end
```

… solved the problem. I'm not sure why, but i have the feeling the storage configuration was not in sync with my Tus upload route at `mount Tus::Server => "/files"`. So somehow to the ".../uploads/cache" path creeped into the Tus location, as you said. Could this have happened assigning the file in the frontend with Uppy?

```js
this.uppy.on('upload-success', (file, response) => {
  const fileData = JSON.stringify({
    id: response.uploadURL,
    storage: "cache",
    metadata: {
      filename: file.name,
      size: file.size,
      mime_type: file.type
    }
  })

  this.fileTarget.value = fileData
  // ...
```

As said, the problem is not occuring anymore and i don't manage to build a self-contained example that reconstructs it. Besides this, the Tus implementation works like a charme on my frontend.

### Regarding the "backend upload" 

Using `Upload.create file: File.open("path...")`, i would like to upload files on the "server side". I am using this mostly in my development process in order to seed my app with records and uploads, e.g. in `seeds.rb`. Especially for the frontend development it's handy to have a good set of exemplary uploads (images, videos, etc.) and (re)uploading them by hand can become a pain. 

As it's only for dummy material and i never used it in production it's not that "necessary". Maybe i could just change my storage to `Shrine::Storage::FileSystem` for the cache while seeding the database and switch back once all files have been processed.

Thanks again for your support!

**Comment by janko** [comment]
For seeding you can upload files directly to the permanent storage and directly assign the data to the column. This avoids the temporary storage altogether.

```rb
upload = Upload.new
uploaded_file = upload.file_attacher.store! Rails.root.join("path-to-file.jpg").open("rb")
upload.file_data = uploaded_file.to_json
upload.save
```

I'll close this issue now as there doesn't appear to be any problem with Shrine itself.
