### ISSUE TITLE
Nested form not saving to storage

### ISSUE THREAD

**Issue by JetsonDavis** [shrinerb/shrine#395]
I followed to doc about Shrine and nested form fields @ https://github.com/shrinerb/shrine/blob/master/doc/multiple_files.md.  Im using Uppy to upload multiple files.

When I save the record, the cache files are being stored properly in the associated table, but the job does not upload to the store and change the associated records from cache to store.

Any advice?

Thanks!

**Comment by janko** [comment]
Could you reproduce this in a self-contained example? The official Rails demo app does the same, and there promotion works, so I don’t know what’s different in your app. You can find a template in CONTRIBUTING.md.

**Comment by JetsonDavis** [comment]
Hey Janko,

You are absolutely right - it is in the rails example.  I was returning from my form:

`image[image_attributes][_hash_][video_data]` instead of `image[image_attributes][_hash_][video]`

Any reason you use a random hash here instead of sequentially numbering the attachments?

Thanks for the quick reply - much appreciated!

**Comment by janko** [comment]
For sequentially numbering attachments, we'd have to first count how many nested records are there so far (in case we're adding more to an existing parent record), and start numbering from there. Since for Rails it doesn't matter what you use for keys, I chose a random string.
