### ISSUE TITLE
2.19.1 release on Rubygems without GitHub Tag, Version Increase or Changelog

### ISSUE THREAD

**Issue by klaustopher** [shrinerb/shrine#397]
Hey there,

I just got a ping that there is a new version `2.19.1` of Shrine available on Rubygems: https://rubygems.org/gems/shrine/versions/2.19.1

- There is no [GitHub Release](https://github.com/shrinerb/shrine/releases) for this Version
- There is no [Changelog Entry](https://github.com/shrinerb/shrine/blob/master/CHANGELOG.md)
- The current master has `2.19.0` as `Shrine.version`: https://github.com/shrinerb/shrine/blob/bcc2c5328f007a884fb6de15edc758fbc144544f/lib/shrine/version.rb

Is this a legit release? If so, could the according entries be added?

Thank you!

**Comment by klaustopher** [comment]
The changes look legit:

```
› diff -r /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.0 /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.1
diff -r /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.0/CHANGELOG.md /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.1/CHANGELOG.md
0a1,4
> ## 2.19.1 (2018-07-20)
>
> * Bring back support for Ruby 2.3 (@janko)
>
diff -r /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.0/lib/shrine/storage/file_system.rb /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.1/lib/shrine/storage/file_system.rb
156c156
<           if Dir.empty?(pathname) && pathname != directory
---
>           if dir_empty?(pathname) && pathname != directory
190a191,201
>       if RUBY_VERSION >= "2.4"
>         def dir_empty?(path)
>           Dir.empty?(path)
>         end
>       else
>         def dir_empty?(path)
>           Dir.foreach(path) { |x| return false unless [".", ".."].include?(x) }
>           true
>         end
>       end
>
diff -r /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.0/lib/shrine/version.rb /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.1/lib/shrine/version.rb
11c11
<     TINY  = 0
---
>     TINY  = 1
diff -r /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.0/shrine.gemspec /Users/klaustopher/.rvm/gems/ruby-2.6.3/gems/shrine-2.19.1/shrine.gemspec
7c7
<   gem.required_ruby_version = ">= 2.4"
---
>   gem.required_ruby_version = ">= 2.3"
```

**Comment by janko** [comment]
Thanks for reporting. I didn't know what is the protocol when releasing a version that's not based off of `master`. I can change `Shrine.version` and move the CHANGELOG entry to a `2.19.1` section (currently it's under `3.0.0 (unreleased)`).

But I don't see how I can create a GitHub release, because I don't see how I can create a git tag, since the commit was added to `master` only after the `3.0.0` work has already started.

**Comment by klaustopher** [comment]
Hmm, maybe branching off a 2-19-stable branch?

But I don't want to break/change your whole release process. Just having an entry in the CHANGELOG would be sufficient for me ;)

**Comment by janko** [comment]
Looking at the Sequel project, it seems that Jeremy was able to create a git tag for the regression release.

Commit history for 5.7.1:

<img width="1012" alt="Screenshot 2019-07-23 at 11 08 20" src="https://user-images.githubusercontent.com/795488/61698935-3c20c600-ad3a-11e9-847f-fe88f727dcdf.png">

Commit history for 5.8.0:

<img width="1044" alt="Screenshot 2019-07-23 at 11 08 35" src="https://user-images.githubusercontent.com/795488/61698950-4642c480-ad3a-11e9-9b03-d4ba77b82caa.png">

There is probably some git magic that can be done without creating a branch. I think `git push --tags` might be the way to go, if I can still find that commit I'll try it out.

**Comment by klaustopher** [comment]
Thanks for taking care 👍

**Comment by janko** [comment]
Ok, `git push --tags` worked, there is now a `v2.19.1` tag and it appears in GH releases.

I've decided to leave the CHANGELOG and `Shrine.version` unchanged on `master`, as I don't want to dirty the git history (note that on `v2.19.1` tag they are updated). For changing Shrine version I'd have to create a `Bump to X.Y.Z` commit, but I want those to always be the last commit in the release and imply the git tag.
