### ISSUE TITLE
DerivationEndpoint in Rails Engines

### ISSUE THREAD

**Issue by tomasc** [shrinerb/shrine#400]
### Brief Description
`DerivationEndpoint` mounted inside Rails Engine does not take into account the path the Engine is mounted at.

### Expected behavior
```ruby
MyRailsEngine.routes.draw do
  mount MyUploader.derivation_endpoint, at: "media"
end

Rails.application.routes.draw do
  mount MyRailsEngine, at: "my/path"
end

my_uploader.derivation_url(…) # => "my/path/media/…"
```

### Actual behavior
The `DerivationEndpoint` is only the path it is mounted at, not recogniznig it might be nested.

```ruby
my_uploader.derivation_url(…) # => "media/…"
```

### Simplest self-contained example code to demonstrate issue
See above

### System configuration
**Ruby version**: 2.6.3p62

**Shrine version**: 2.19.3

**Comment by janko** [comment]
Shrine doesn't know anything about Rails or Rails engines, nor how the derivation endpoint was mounted (whether it's in Rails routes or `config.ru`). Note that it's possible to mount multiple derivation endpoints for the same uploader at different paths, when you need different behaviour.

For this reason, the [`:prefix`](https://github.com/shrinerb/shrine/blob/v2.19.0/doc/plugins/derivation_endpoint.md#prefix) option was added:

```rb
plugin :derivation_endpoint, secret_key: "...", prefix: "my/path"
```
```rb
file.derivation_url(…) # => "/my/path/media/…"
```

Rails engines should ideally have a wrapper method for URLs which automatically prepend their path prefix. Alternatively, a convenience API for Rails could be added to the [`shrine-rails`](https://github.com/abepetrillo/shrine-rails) gem.

**Comment by tomasc** [comment]
Makes sense, I do not see any railties in Shrine's code, so I understand there is not Rails specific integration (yet :-)).

For now, this can be solved by naming the `DerivationEndpoint` mount point:

```ruby
MyRailsEngine.routes.draw do
  mount MyUploader.derivation_endpoint, at: "media", as: my_uploader_derivation_endpoint
end
```

And then using that named route in the plugin config:

```ruby
plugin :derivation_endpoint, 
       prefix: -> { MyRailsEngine.routes.url_helpers.my_uploader_derivation_endpoint_path[1..-1] }
```

I needed to use lambda for this to be evaluated later, once the router is initialized. Also the Rails paths start with "/" which needs to be stripped (hence `[1..-1]`).

**Comment by janko** [comment]
Thanks a lot for posting the solution. Ok, at the very least `derivation_endpoint` could handle a leading slash; I found myself not remembering whether leading slash is ok when writing the answer, which is not a great sign 😛

**Comment by tomasc** [comment]
The only catch is that (in my case in tests)

```ruby
@status, @headers, @body = MyUploader.derivation_response(env)
``` 

fails with

```ruby
Shrine::Error: request path must start with "/#<Proc:… (lambda)>"
```

**Comment by janko** [comment]
Hmm, the problem is that `Shrine.derivation_response` is not handling a dynamic `:prefix`. The problem is that it can't handle it, because dynamic options must be executed in context of a `Shrine::Derivation` instance, but since the check that caused the exception is executed before the derivation URL is even parsed, there is no `Shrine::Derivation` instance available.

So, in summary, a dynamic `:prefix` doesn't work with `Shrine.derivation_response`. I would recommend that you enter the engine path value directly, even though that isn't DRY.

Either that, or you can set it later on once the routes have initialized. When you load a Shrine plugin again, existing options are merged:

```rb
class MyUploader < Shrine
  plugin :derivation_endpoint, secret_key: "..." # load first without prefix
end
```
```rb
# add prefix after the routes have initialized:
MyUploader.plugin :derivation_endpoint, prefix: MyRailsEngine.routes.url_helpers.my_uploader_derivation_endpoint_path[1..]
```

**Comment by tomasc** [comment]
Thanks, yes, that's what I ended up doing in the end.

**Comment by jrochkind** [comment]
sounds like clear example docs for Rails might be in order. 

It's unfortunate that you need a kind of hack to use a prefix, as I think it would be very unusual NOT to use a prefix here.

**Comment by tomasc** [comment]
@jrochkind yes. In fact if the `DerivationEndpoint` is WITHOUT a prefix, but in Rails Engine mounted on a path (not on a root), the derivation URLs will be incorrect.
