### ISSUE TITLE
Add clear_prefixed/delete_prefixed method for each Storage adapter

### ISSUE THREAD

**Issue by jrochkind** [shrinerb/shrine#409]
Similar to ActiveStorage delete_prefixed. 

I wound up needing it for some custom use of low-level Shrine::UploadedFile api, when I was constructing some related files under the same prefix myself. 

Every Storage adapter would have to provide it's own implementation. 

https://api.rubyonrails.org/classes/ActiveStorage/Service.html#method-i-delete_prefixed

https://github.com/rails/rails/search?q=delete_prefixed&unscoped_q=delete_prefixed

**Comment by janko** [comment]
This would also help with automatically deleting processed files generated by `derivation_endpoint` when the associated record is deleted (like [Active Storage does](https://github.com/rails/rails/blob/6bf2e59becc0d9cf884f28eac61d7f0aeae75c23/activestorage/app/models/active_storage/blob.rb#L219)).

**Comment by jrochkind** [comment]
@janko tell me what you want the method name/signature to be, and I can make a PR for S3 and local file system. 

The harder part is how/where we document this -- both for writers of storage adapters and users of such -- and how we try to get all adapters (some of which are in other repos, including third-party repos?) to implement this. Not sure about any of that. 

But I can give you code  for S3 and local file system! Oh, and tests (I find non-rspec tests painful, but I'll figure it out!)

**Comment by janko** [comment]
@jrochkind For the naming, I lean slightly more towards `#delete_prefixed` naming, so if it's ok with you we can use that.

> The harder part is how/where we document this

The "[Writing a Storage](https://github.com/shrinerb/shrine/blob/master/doc/creating_storages.md)" is the de facto guide for storage implementers, so we should document it there. Then we can also add it to individual docs for each storage (like we currently document `#clear!`).

> and how we try to get all adapters (some of which are in other repos, including third-party repos?) to implement this

I guess opening issues and sending PRs would be the best way.

Additionally, we could potentially have the Shrine's storage linter warn when `#delete_prefixed` isn't implemented. But I'm not too keen on that idea, especially because for now that method won't be used by Shrine.

> But I can give you code for S3 and local file system!

Great, thanks! 👍

**Comment by jrochkind** [comment]
In storages where it matters, like local FileSystem -- if you delete_prefixed, should it delete the parent directory you mentioned too? Or leave it there, empty?

ActiveStorage leaves it there empty. It's a bit simpler implementation to just delete it. Shrine::Storages::S3 seems to always lazily (re-)create any parent dirs needed on demand, so doesn't seem to be a problem to delete it.

**Comment by jrochkind** [comment]
It looks to me like existing implementation of Shrine::Storage::FileSystem tries it's best not to leave empty directories sitting around, so I will use that same principle for `delete_prefixed`, even though the ActiveStorage version seems to have code that intentionally leaves the empty directory sitting around, not sure why.

**Comment by jrochkind** [comment]
I will add `delete_prefixed` to the linter the same way `clear!` is currently handled, in an `if storage.respond_to?(:delete_prefixed)` guard. So if it's there, it will be tested. 

Personally, I think the linter should probably have a "maximal" mode, where it insists that some of these optional methods _are_ there. So you know if you have a 'maximal compatible' storage, you can count on using clear!, `delete_prefixed`, etc. But that is a separate issue, for adding `delete_prefixed` it makes sense to treat it like the already existing optional `clear!`.
