### ISSUE TITLE
NoMethodError: undefined method `promote' for Shrine::Attacher:Class

### ISSUE THREAD

**Issue by mohnstrudel** [shrinerb/shrine#411]
My setup is almost identical with this one: https://github.com/shrinerb/shrine/issues/200
Still getting the error when using Shrine together with Sidekiq

---

### Error
```ruby
2019-09-18T15:41:14.735Z pid=22765 tid=ovvg25t29 WARN: NoMethodError: undefined method `promote' for Shrine::Attacher:Class
2019-09-18T15:41:14.735Z pid=22765 tid=ovvg25t29 WARN: /Users/anton.kostin/projects/rails_sandbox/freelance/transmogram/app/jobs/shrine_backgrounding/promote_job.rb:6:in `perform'
```

### Uploader
```ruby
require "image_processing/mini_magick"

class ImageUploader < Shrine
  #plugins and uploading logic

  plugin :processing # allows hooking into promoting
  plugin :versions   # enable Shrine to handle a hash of files
  plugin :delete_raw # delete processed files after uploading

  plugin :validation_helpers
  plugin :determine_mime_type

  Attacher.validate do
    validate_min_size 1, message: "must not be empty"
    validate_max_size 10.megabytes, message: "is too large (max is 10 MB)"
    validate_mime_type_inclusion %w[image/jpeg image/png image/tiff]
    validate_extension_inclusion %w[jpg jpeg png tiff tif]
  end

  process(:store) do |io, context|
    versions = { original: io } # retain original

    # download the uploaded file from the temporary storage
    io.download do |original|
      pipeline = ImageProcessing::MiniMagick.source(original)

      versions[:supersmall] = pipeline.resize_to_fill!(50, 50)
      versions[:small] = pipeline.resize_to_fill!(100, 100)
      versions[:medium] = pipeline.resize_to_fill!(269, 202)
      versions[:large] = pipeline.resize_to_fill!(870, 569)
    end

    versions
  end

  Attacher.promote do |data|
    ShrineBackgrounding::PromoteJob.perform_async(data)
  end
  Attacher.delete do |data|
    ShrineBackgrounding::DeleteJob.perform_async(data)
  end
end
```

### Job
```ruby
module ShrineBackgrounding
  class PromoteJob
    include Sidekiq::Worker

    def perform(data)
      Shrine::Attacher.promote(data)
    end
  end
end
```

### Initializer
```ruby
require "shrine"
require "shrine/storage/file_system"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"), # temporary
  store: Shrine::Storage::FileSystem.new("public", prefix: "uploads"),       # permanent
}

Shrine.plugin :activerecord # or :activerecord
Shrine.plugin :cached_attachment_data # for retaining the cached file across form redisplays
Shrine.plugin :restore_cached_data # re-extract metadata when attaching a cached file
# Shrine.plugin :rack_file # for no n-Rails apps

Shrine.plugin :backgrounding
```

### System configuration
**Ruby version**: ruby-2.6.3

**Shrine version**: shrine (2.19.3, 2.18.1)
**Sidekiq version**: sidekiq (6.0.0, 5.2.7)

**Comment by janko** [comment]
Could you create a minimal self-contained example that reproduces the error? The only way I see this exception happening is if you’re using a 3.0 beta version of Shrine (which is clearly not the case, as you said you’re using 2.x).

**Comment by mohnstrudel** [comment]
Thank you for such a quick reply. I will try to spin up a docker container on the weekend.

**Comment by janko** [comment]
Note that it doesn't need to be a Docker container, I was more thinking about a [self-contained script](https://github.com/shrinerb/shrine/blob/master/CONTRIBUTING.md#appendix-b-activerecord-template) which has only the necessary amount of plugins needed to reproduce the error. The point is just that I can run it on my machine, with steps e.g:

1. run this sidekiq command
2. run this ruby script

**Comment by mohnstrudel** [comment]
Utterly strange, no matter what I did, at some point the error was gone and I could not reproduce it.
So, some few steps:
- I put a `byebug` inside of my worker method (`perform(data)`)
- I moved worker class up the hierarchy (i.g. removing `ShrineBackgrounding::`) and then down again
- inbetween a lot of restarts both, the rails server and the sidekiq server

I think the issue can be closed now.
