### ISSUE TITLE
How does Shrine delete files?

### ISSUE THREAD

**Issue by chrishough** [shrinerb/shrine#428]
I am trying to answers these questions, but I am having a hard time locating any documentation on this. We are using the delete_raw plugin. 

- Does it try to delete the file immediately?
- What happens if it can't delete the file? Will it raise some sort of exception?

**Comment by janko** [comment]
If you're talking about the deletion related to the `delete_raw` plugin, then yes, it will delete the file immediately after upload. If the file doesn't exist anymore after upload (e.g. you have moving enabled with `FileSysem` storage), then the exception will be ignored. Any other deletion exceptions will be propagated.

Note that usage questions should be asked on the [Discourse](https://discourse.shrinerb.com) forum, GitHub issues are only for bug reports and sometimes feature requests, so I'll close this issue.

**Comment by chrishough** [comment]
Thank you
