### ISSUE TITLE
NoMethodError: undefined method 'shrine_style_file'

### ISSUE THREAD

**Issue by Jeanluis019** [shrinerb/shrine#429]
### Brief Description
When I run the script to migrate the data from Paperclip to Shrine and the field is null, I get the following error:

`undefined method 'shrine_style_file'`

Code:
```
 def shrine_file(object)
    if object.is_a?(Paperclip::Attachment)
      shrine_attachment_file(object)
    else
      shrine_style_file(object) # This is the line causing the error (This method doesn't exists in the PaperclipShrineSynchronization module).
    end
 end
```

I think this is a typo because I see that the `style_to_shrine_data` method is never called and the names are similar, so the previous method should be the` shrine_style_file` method?

### Actual behavior
Throw an error because it's calling an undefined method.

### System configuration
**Ruby version**:
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

**Shrine version**:
shrine (3.0.1)

[Guide to Migrate From Paperclip](https://github.com/shrinerb/shrine/blob/master/doc/paperclip.md)

**Comment by janko** [comment]
Thanks for reporting, yes, that method was supposed to be called.
