### ISSUE TITLE
uninitialized constant Attachment

### ISSUE THREAD

**Issue by resistorsoftware** [shrinerb/shrine#444]
- Issues are for bug reports only.
- Have a question or unsure if it's a bug, then please inquire on the [forum](https://discourse.shrinerb.com).
---

### Brief Description
Trying to upload a file.

### Expected behavior
Uploaded file

### Actual behavior
↳ app/controllers/sku_controller.rb:8:in `create'
14:47:24 rails.1   | Error in creating Sku file: uninitialized constant Attachment

In a Rails 6 App, in app/uploaders, we have a simple Uploader:

    class ExcelUploader < Shrine
      plugin :determine_mime_type
      plugin :validation_helpers
      Attacher.validate do
        validate_mime_type_inclusion ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], message: 'Is not Excel file!'
      end
    end

We have a Model that includes the uploader

    class Sku < ApplicationRecord
      include ExcelUploader::Attachment(:excel)
    end

### System configuration
2.6.5

**Shrine version**:
3.2.1

**Comment by janko** [comment]
Could you create a fresh Rails app which reproduces the error and share it here? This is the most vanilla Shrine setup, so the issue must be coming from something in the Rails app itself.

**Comment by resistorsoftware** [comment]
Could it be the object I am using? My controller gets these params, and I am thinking this is likely the source of the issue? Do I even need an attacher? I am not processing photos or anything, just uploading an excel file I then expect to be able to parse and use.

SKU CREATE PARAMS: <ActionController::Parameters {"id"=>"c41a16767c0aada1f745bf9dc8a1da51.xlsx", "excel"=>{"id"=>"c41a16767c0aada1f745bf9dc8a1da51.xlsx", "storage"=>"cache", "shopify_domain"=>"discountedfilters.myshopify.com", "metadata"=>{"size"=>49972, "filename"=>"SKU Lookup Table NEW.xlsx", "mime_type"=>"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}}, "controller"=>"sku", "action"=>"create", "sku"=>{"id"=>"c41a16767c0aada1f745bf9dc8a1da51.xlsx"}} permitted: false>
