### ISSUE TITLE
Upgrading Shrine 2.11 to 3.2.1

### ISSUE THREAD

**Issue by burgalon** [shrinerb/shrine#460]
While upgrading from Shrine 2.11 to 3.2.1 I'm encountering error 
```
Shrine::Error: {"original"=>{"id"=>"1c9143fa7dcef03f68861e7adb4c9c78.jpg", "storage"=>"store", "metadata"=>{"filename"=>"facebook_profile_photo.jpg", "size"=>11041, "mime_type"=>"image/jpeg", "width"=>200, "height"=>238}}, "thumb"=>{"id"=>"a5733b550ae335b7049a881fbaa84cf3.jpg", "storage"=>"store", "metadata"=>{"filename"=>"s320170328-4-wsps69.jpg", "size"=>8887, "mime_type"=>"image/jpeg", "width"=>200, "height"=>200}}} isn't valid uploaded file data
```

It seems like this is a result of missing `id` and `storage` at the top-level of the JSON.
Is there some documentation of the database migration that should be done?

Also it seems like I need to migrate the JSON from the versioning plugin to the derivative plugin

**Comment by jrochkind** [comment]
Your diagnosis is correct!  Does the following help?

https://shrinerb.com/docs/upgrading-to-3#migrating-versions

**Comment by burgalon** [comment]
Sweet Jesus! I went through the upgrade page and missed the versions_compatibility part. Thank you!
