### ISSUE TITLE
Preventing remote_url to encode url

### ISSUE THREAD

**Issue by adbmdp** [shrinerb/shrine#461]
Hello,

I'm using the remote_url plugin to download some files that are on a Minio server.
On the Minio server all files names are not encoded the same way.
For exemple "é" characters are sometimes encodes like this `e%CC%81` or like that `%C3%A9`
So to get the file i have to call it with exactly the right format, even in my browser.

The probem is that remote_url tries to re-encode the url.
How can i prevent remote_url (and the down gem i guess) to re-encode the url ?

MyShrine version is 2.0

Thanks

**Comment by janko** [comment]
Try upgrading to latest Shrine 2.x version and Down to the latest 5.x version. That should fix the issue.

**Comment by adbmdp** [comment]
Thanks you!  I'll try that and tell you if it works.
Something like that in my gem file?
`gem "shrine", "2.19.4"`

Do i have to install Down also, to force a 5.x version?

**Comment by janko** [comment]
Yes, put the following in your Gemfile:

```rb
# Gemfile
gem "shrine", "~> 2.19"
gem "down", "~> 5.0"
```

**Comment by adbmdp** [comment]
As there is a dependency, how can i force down to a 5.x version?

```
Bundler could not find compatible versions for gem "down":
  In Gemfile:
    down (~> 5.0)

    shrine (~> 2.19) was resolved to 2.19.3, which depends on
      down (~> 4.1)
```

**Comment by janko** [comment]
[Shrine 2.19.4](https://rubygems.org/gems/shrine/versions/2.19.4) is the latest 2.x version, and it allows Down 5.x.

**Comment by adbmdp** [comment]
Thanks a lot for your help!
Btw i think it's time for me to upgrade to Shrine 3.x :-)
