### ISSUE TITLE
Should some Attacher state be preserved on model reload?

### ISSUE THREAD

**Issue by jrochkind** [shrinerb/shrine#463]
The activerecord plugin overrides AR model `reload` to completely erase the attacher class. (It will be lazily re-created from scratch on next access). 

https://github.com/shrinerb/shrine/blob/b5fc2e1432e51e6fde87c120bc6cf6abeb286c68/lib/shrine/plugins/activerecord.rb#L56-L60

(sequel plugin does something similar, but I have no experience with it myself). 

This means that when you reload an AR model, *all* state on the shrine attacher is erased. 

This is convenient for making sure you haven't accidentally preserved any state that becomes invalid on model reload.  You can't have, you have preserved no state. 

However, it isn't entirely consistent with what ActiveRecord reload does. ActiveRecord does not actually erase *all* instance state.  One way to get the same AR record with all instance state erased might be:  

    my_model_instance = MyModel.find(my_model_instance.id)

That would replace the model instance with one reloaded from the db, with _all_ instance state erased. But that isn't what AR `reload` does.  To illustrate the difference, if an AR model has non-db-persisted , say created with `attr_accessor :non_persisted_attr` -- if you were doing a `MyModel.find` as above, the value of ` non_persisted_attr` would of course be lost. But if you do `my_model.reload`, the value of `non_persisted_attr` would be preserved. 

However, _all_ state from the shrine attacher is thrown out on `reload`, as a result of the implementation above. 

This includes throwing out any shrine `context` that might be set. Does it make sense to throw out any persistent shrine `context` on model reload?  Maybe not. 

The implementation could try to save the context and then restore it in the newly created attacher instance.... 

But it might make more sense to have the activerecord `reload` implementation call `attacher.reload` instead of doing `instance_variable_set(:"@#{name}_attacher", nil)`

1. It is much cleaner code than breaking encapsulation with `instance_variable_set`, just using the public `reload` method
2. It is probably cleaner code than any method of trying to "save and restore" context specifically
3. Is context the *only* thing we want to preserve? It's the only thing I can think of, but really the semantics should probably be "reload the things that come from the db, preserve everything else", because that's the semantics of AR reload. Rather than "whitelisting" specifically what to preserve. 
4. The existing [Attacher#reload method](https://github.com/shrinerb/shrine/blob/b5fc2e1432e51e6fde87c120bc6cf6abeb286c68/lib/shrine/plugins/entity.rb#L104-L116) should be have those semantics already. If any state is preserved accross an `attacher.reload` that is invalid with the new reloaded underlying data -- that probably constitutes a bug in `Attacher#reload` even aside from the context of the `model.reload` call, and should be fixed independently -- because there can be call sites that call `Attacher#reload` directly, it's a public method.

**Comment by jrochkind** [comment]
For what it's worth:

If I change the line in activerecord plugin `instance_variable_set(:"@#{name}_attacher", nil)`, to instead be:

   send(:"#{name}_attacher").reload

All shrine tests still pass. 

(If I just remove the line with no replacement, there are 3 test failures, so there are tests that fail on improper reload behavior).

**Comment by janko** [comment]
@jrochkind Thank you for the suggestion, you make a solid case. This would make sense for me as well, especially considering that it's consistent with how `ActiveRecord::Base#reload` and `Sequel::Model#reload` work. I will go ahead and make that change 👍

**Comment by dmitry** [comment]
@janko @jrochkind 
After an upgrade to the 3.3.0 I found an issue with `reload` of a model with shrine attachers and `attribute_changed?` behaviour. Previously it reset attribute changes (via dirty activemodel module), and now it's still dirty (changed) even after `reload` called. Any idea what happened? ActiveRecord by design should restore previous attribute values state (before changes) and `changed?` should back to `false`.

I've tried to use https://github.com/shrinerb/shrine/commit/28378d92fe2efe4ba6d053973e39e14d2560e5c9 from the latest master branch, and still it doesn't work correctly.

Current fix is to use `record = Model.find(record.id)` but I think shrine should work correctly in terms of rails activerecord conventions.

**Comment by janko** [comment]
Thanks for the report. We should probably be able to fix this by setting `@previous` to nil in `Attacher#reload`, which is used in the Attacher for dirty tracking. I will think about whether that won't break existing use cases, but I think it should be safe.

Just to confirm, Active Record is correctly returning that no attributes have changed after `#reload`, but the `Attacher#changed?` method is returning true, is that correct?

**Comment by janko** [comment]
@dmitry I've just pushed https://github.com/shrinerb/shrine/commit/a792dce5cd6b48057e5640e0881e966df9ef8927 which resets `@previous` in `Attacher#reload`, so `Attacher#changed?` should return `false`.

Let me know if that fixes your issue. It's also possible I misunderstood the problem to begin with 😛

**Comment by dmitry** [comment]
@janko thank you, it's fixed after the https://github.com/shrinerb/shrine/commit/a792dce5cd6b48057e5640e0881e966df9ef8927.

**Comment by dmitry** [comment]
> Just to confirm, Active Record is correctly returning that no attributes have changed after `#reload`, but the `Attacher#changed?` method is still returning `true`?

While I check `some_field_changed?` previously it returned `true`, now it's `false` after the `reload`. So it works now as expected. Thank you again.
