### ISSUE TITLE
add_derivative(s) can result in "orphaned" derivatives in storage

### ISSUE THREAD

**Issue by jrochkind** [shrinerb/shrine#468]
I think this may be a bug, but possibly you will not consider it a bug? if not a bug, it may require docs?

When using add_derivative(s), if some existing derivatives end up being replaced, the replaced files will not be deleted from storage.  They will be left on storage, but now "orphaned" not referred to by any models.  This might surprise some developers, and lead to lots of orphaned derivatives, filling up storage and/or creating extra costs to storage provider. It can be difficult to find these 'orphaned' files, to figure out which files on your storage represent derivatives no longer referenced. 

```ruby
# activerecord
some_model.image_attacher.add_derivatives({
  one: StringIO.new("old one"),
  two: StringIO.new("old two)
})
some_model.save!

some_model.image_derivatives.keys
# => [:one, :two]
existing_one = some_model.image_derivatives[:one]

some_model.image_derivatives.add_derivative(:one, StringIO.new("new one"))
some_model.save!

existing_one.exists? #=> true !!!
```

`existing_one` is no longer referred to in `some_model.derivatives`, but is still existing on storage. 

The same basic issue occurs if you use the somewhat lower-level `merge_derivatives` instead of `add_derivative`/`add_derivatives`. 

One way for code using shrine to ensure no derivatives get orphaned when replaced with add/merge, in a generic way, might be something like this:

```ruby
previous_derivatives_files = some_model.image_attacher.map_derivative( some_model.image_derivatives) 

some_model.add_derivatives({ :one => file, :two => other_file})
some_model.save!

current_derivative_files = some_model.image_attacher.map_derivative( some_model.image_derivatives)

replaced_derivative_files = previous_derivative_files - current_derivative_files 
some_model.image_attacher.delete_derivatives(replaced_derivative_files)
```

Adding concurrency controls with `atomic_persist` might be another wrinkle.

**Comment by janko** [comment]
Short answer is that deleting derivatives is not safe until you've persisted the new derivatives. If the replaced derivatives were deleted immediately, and for whatever reason it took longer time until the record was persisted, the app could be trying to retrieve the deleted derivatives.

It's possible we could add an option for deleting previous derivatives, which the user can call on their own responsibility. However, it's still generally safer to delete files once the database isn't referencing them anymore, like what you posted. I agree it should be documented that potentially replaced derivatives are not being deleted.

FWIW, I believe you can shorten the above code a bit:

```rb
new_derivatives = { :one => file, :two => other_file}
replaced_derivatives = some_model.image_derivatives.slice(*new_derivatives.akeys)

some_model.add_derivatives(new_derivatives)
some_model.save!

some_model.image_attacher.delete_derivatives(replaced_derivatives)
```

**Comment by jrochkind** [comment]
I think the `slice` wont' work if the derivatives are "nested" -- that's why I used "map_derivative" to flatten them. 

As this demonstrates, it's a bit tricky to figure out how to _get_ the list of derivatives that should be deleted, and then delete them. 

I think users maybe could use some guidance here. Either code or docs -- but I'm not sure which either should be. It's not clear to me what the API for code would be that could be used in a flexible way -- I agree with your analysis that it's not safe to delete old ones until new ones are persisted. the trick is getting the list of ones that *will* need to be deleted, and then deleting them at the right time, when shrine de-couples persistence from everything else. 

Maybe the API is like a `with_derivative_cleanup do` method, that takes a snapshot of current derivatives, yields (block should change derivatives and persist), and then after yield takes a snapshot of current derivatives, so it can diff and delete ones that were removed. But that starts sounding a bit complex/fragile, not sure. 

Alternately, it could at least be doc'd to warn people it's an issue -- if I weren't thinking carefully, I think would not have thought about/noticed it, and if replacing derivatives a lot, my storage would be filling up with hard-to-find orphaned files. 

As an aside, I'm also a bit scared of the `delete_derivatives(list_of_derivatives)` method -- if you accidentally pass it `nil` as an arg, you'll end up deleting the *current* derivatives from storage, as that's it's default argument.  this makes me feel like it's risky to use it.

**Comment by janko** [comment]
That last thing is a good point, that method should probably differentiate between nil passed and no argument passed.

**Comment by janko** [comment]
Thanks for the suggestions. I couldn't think of a proper API for this, and since I don't consider this will be a very common scenario, for now I've just added a warning about replacing existing derivatives.

Regarding your last concern about `Attacher#delete_derivatives`, it actually blows up if you pass `nil` to it, and doesn't delete any derivatives, so we should be good here.

**Comment by jrochkind** [comment]
Cool. 

> If this is your case, make sure to save a reference to the old derivatives before assigning new ones, and then delete them after persisting the change.

You do have a recipe for this, I think, at https://shrinerb.com/docs/changing-derivatives#reprocessing-all-derivatives

(I may not have known/remembered that when I filed this issue)
