### ISSUE TITLE
remove_attachment plugin prevents files deletion

### ISSUE THREAD

**Issue by Roko131** [shrinerb/shrine#473]
### Brief Description
When using `remove_attachment` plugin, while
- Model already have an image.
- Checking 'remove_image' checkbox
- Selecting a new image file to upload

The new file is uploaded but the old file remains on the store server without being deleted

### Expected behavior
Old file should be deleted.

### Actual behavior
Old files that should be replaced are not being deleted.

### Simplest self-contained example code to demonstrate issue
Basically if you have a model already with image.
And you update it with a new image while still passing the revert_image as true
The previous file will not be deleted.
```ruby
post.update(remove_image: true, image: File.open("#{TEST_FOLDER_PATH}/image2.png", 'rb'))
```

So in test 3 - since we are doing it 5 times - there will be an extra 5 files at the server.

```ruby
require 'active_record'
require 'shrine'
require 'shrine/storage/file_system'
require 'image_processing'

TEST_FOLDER_PATH = '/path/to/folder/with/images'
TEST_NUM = 1 # just adding a single file - works
TEST_NUM = 2 # adding file, then deleting it - works fine
TEST_NUM = 3 # after already having an image, if selecting a new image AND checking to remove-> old files leftovers

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(TEST_FOLDER_PATH, prefix: 'results/cache'), # temporary
  store: Shrine::Storage::FileSystem.new(TEST_FOLDER_PATH, prefix: 'results'),       # permanent
}

Shrine.plugin :activerecord
Shrine.plugin :remove_attachment # allows to delete attachments through checkboxes on the web form

class MyUploader < Shrine
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }

class Post < ActiveRecord::Base
  include MyUploader::Attachment(:image)
end

case TEST_NUM
when 1
  # create image
  post = Post.create(image: File.open("#{TEST_FOLDER_PATH}/image1.png", 'rb'))
when 2
  # create image
  post = Post.create(image: File.open("#{TEST_FOLDER_PATH}/image1.png", 'rb'))

  # deleting it afterwards with remove_image
  post.reload
  post.update(remove_image: true)
when 3
  # create image with derivatives (derivatives created at background job)
  post = Post.create(image: File.open("#{TEST_FOLDER_PATH}/image1.png", 'rb'))
  5.times do # will cause extra 5 files on the server
    post.reload
    # deleting them afterwards with remove_image, together with remove_image but
    # there are leftovers files
    post.update(remove_image: true, image: File.open("#{TEST_FOLDER_PATH}/image2.png", 'rb'))
  end

end


```

### System configuration
**Ruby version**:
`ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
**Shrine version**:
`shrine (3.2.1)`

**Comment by Roko131** [comment]
Currently my  workaround for solving it:

Adding flag to indicate that a file is being uploaded:
```ruby
class MyUploader < Shrine
  Attacher.validate do
    @being_uploaded = true
  end
end
```

Check that flag at `remove_attachment`, and basically disable it if flag exists, overriding `remove=` method:

```ruby
def remove=(value)
  @remove = value

  # skip deletion (which doesn't work in this case anyway bcz uploading new files)
  return if @being_uploaded

  change(nil) if remove?
end
```

**Comment by BKSpurgeon** [comment]
@Roko131 I can confirm that I could replicate your bug report, but I do not have an immediate solution handy (at least without further study):

Here is a quick hack which might (not) suit you or others:

```ruby
   post.update(remove_image: true)
   post.update(image: File.open("#{TEST_FOLDER_PATH}/image2.png", 'rb'))
```

rgds

Ben

**Comment by janko** [comment]
Thanks @Roko131 for the report, and @BKSpurgeon for reproducing. I think there is a fairly easy fix for this, I will push it out shortly.
