### ISSUE TITLE
Clarification on Shrine validations

### ISSUE THREAD

**Issue by aghalarp** [shrinerb/shrine#495]
First of all, thanks for all the work you guys do on Shrine, it's a great library. Apologies for asking my question here instead of on the Discourse page, but I'm having difficulties creating an account there (unable to login, not receiving email confirmation).

I'm working with Shrine's validations plugin and I want to make sure I understand how things are working beneath the hood.

My understanding is that Shrine's validations occur separately from the attached model's validations. Shrine's validations occur upon file assignment, whereas the AR validations occur upon record update/save.

My question is, does Shrine's validations actually prevent file uploading from occurring? The fact that the `remove_invalid` plugin exists makes me believe otherwise.

Also, in the situation where a file passes Shrine's validations but later fails the model's validations, we'd have to manually destroy the attached file ourselves, is this correct? The `remove_invalid` plugin would be of no use in this situation, since it's only concerned about the Shrine validations?

Thanks - and apologies again for asking my question here.

**Comment by aghalarp** [comment]
After reading around a bit, I think I have a clearer understanding about the order of operations:

1. File assignment occurs and the file gets uploaded to the cache store
2. Shrine-level validations are ran. Any validation errors are merged into the the ActiveRecord errors hash.
3. If Shrine validations fail and we're using the `remove_invalid` plugin, the file assignment is reverted and the cached file will be deleted (or will it?)
4. If Shrine validations pass, but model-level validations fail (after calling #save, for example), then the cached file is not promoted to permanent storage. The file remains in the cache, which is useful because we can re-use it on the next file promotion attempt (ie. the user resubmits the form after fixing validation errors). If the user abandons resubmission at this point, the file will remain in the cache forever until we clear it ourselves (via cronjob or some other mechanism).

Am I mostly on target here?

**Comment by BKSpurgeon** [comment]
Let me preface all of this by saying: I am by no means an expert. Perhaps someone with a better understanding can correct any shortcomings below.

> My question is, does Shrine's validations actually prevent file uploading from occurring? The fact that the remove_invalid plugin exists makes me believe otherwise.

Shrine is designed with a plugin architecture. If you want additional behaviour, then you add the plugin. If you don't want the plugin, then things should work as expected without the plugin. Plugins basically add/modify existing behaviour by overriding it. Secondly, it depends on your workflow. Some people may want to upload their files directly to the bucket. In this case, there is no way that the uploads can be prevented by the validations plugin or the remove_invalid. Other people may want the server to upload the file to the bucket. I suppose that this is what you were wanting answered.

Now to your question:

(i) Let's assume you are using the [validation](https://shrinerb.com/docs/plugins/validation) plugin and ARE NOT using the `remove_invalid` plugin. How does it work?

https://github.com/shrinerb/shrine/blob/c039a250845c4df7cac7d9e6f5ca81f985c744eb/lib/shrine/plugins/validation.rb#L33

```ruby
        def attach_cached(value, validate: nil, **options)
          result = super(value, validate: false, **options)
          validation(validate)
          result
        end
```

This is a plugin that basically adds behaviour to `atttacher` instances. First [super is called and the file is uploaded to the bucket](https://github.com/shrinerb/shrine/blob/c039a250845c4df7cac7d9e6f5ca81f985c744eb/lib/shrine/attacher.rb#L95). Then the validation occurs after it.

To answer your question, no, the validations plugin does not prevent the upload from occurring. And if there are validation errors, then it does not wive it from your storage. If you want the file wiped, then you'll have to add the `remove_invalid` plugin.

(ii) Let us consider the situation where you have the `remove_invalid` plugin

[This basically ropes in the `validations` plugin](https://github.com/shrinerb/shrine/blob/c039a250845c4df7cac7d9e6f5ca81f985ac744eb/lib/shrine/plugins/remove_invalid.rb) whether you like it or not. And if there are any errors, [then it wipes it from your storage](https://github.com/shrinerb/shrine/blob/c039a250845c4df7cac7d9e6f5ca81f985c744eb/lib/shrine/plugins/remove_invalid.rb#L15).

Here the upload occurs, but is deleted if the validation fails.

**Comment by BKSpurgeon** [comment]
>     File assignment occurs and the file gets uploaded to the cache store

Yes. (some people don't have a cache but that's another matter)

>    Shrine-level validations are ran. Any validation errors are merged into the the ActiveRecord errors hash.

Yes

>    If Shrine validations fail and we're using the remove_invalid plugin, the file assignment is reverted and the cached file will be deleted (or will it?)

It will be deleted from the bucket

>     If Shrine validations pass, but model-level validations fail (after calling #save, for example), then the cached file is not promoted to permanent storage. 

YES, but if you are using the `remove_invalid` plugin, the the file you have uploaded to the bucket will be destroyed, and the previous file you had (if any) will be restored to the record.

> The file remains in the cache, which is useful because we can re-use it on the next file promotion attempt (ie. the user resubmits the form after fixing validation errors). If the user abandons resubmission at this point, the file will remain in the cache forever until we clear it ourselves (via cronjob or some other mechanism).

It will remain the cache so long as you are are not using the `remove_invalid` plugin.

As a general rule: shrine does not delete anything from the cache, unless you tell it to specifically. You can add what's called a life cycle rule - most bucket providers should have this. This means that if a file is sitting in the cache for a set period of time, then the bucket will automatically delete it. It saves you from running cron jobs.

**Comment by aghalarp** [comment]
Thanks! Really appreciate all your insights.

 > YES, but if you are using the `remove_invalid` plugin, the the file you have uploaded to the bucket will be destroyed, and the previous file you had (if any) will be restored to the record.

Does this mean that the `remove_invalid` plugin hooks into the model-level validations? I would think that this plugin would only be concerned with Shrine/Uploader validations.

**Comment by jrochkind** [comment]
In general, I have found it best to assume that there WILL be "leftover" things in the 'cache' storage. The `remove_invalid` plugin might be trying to avoid that in one particular circumstance, but there are too many other circumstances too. 

Like if you are using "direct uploads" (as is often a really good idea, and you may some day end up there even if you aren't there now), the file could wind up on cache and the user could never even press the 'save' button to trigger back-end validations or model creation at all, and the file would just be there unknown by the backend at all. 

This is one of the reasons to separate cache from storage in the first place -- so you can run routine cleanups of "leftover" files on cache, AND because cache consists of *unsafe files*, that may not have been validated or otherwise proven acceptable. 

So personally I don't think it's worth bothering with `remove_invalid` and trying to figure out in what circumstances it may not (by bug or intention) not succesfully clean up.  Just accept that cache is full of temporary and possibly leftover stuff that needs to be cleaned.  I'd be more interested in thinking about patterns or plugins to make sure not to display or provide access to files that are only on `cache` and not yet on `store` which may not have been tested and approved for use. (hypothetically something like anti-virus might be another thing you'd want to do which files on cache won't have done to them yet).

**Comment by aghalarp** [comment]
Appreciate your help! I'll go ahead with the simplest approach and rely on a bucket lifecycle rule to clear the cache, as was recommended.
