### ISSUE TITLE
s3-multipart does not fire complete event without manual intervention

### ISSUE THREAD

**Issue by goelinsights** [shrinerb/shrine#496]
- Issues are for bug reports only.
- Have a question or unsure if it's a bug, then please inquire on the [forum](https://discourse.shrinerb.com).
---

### Brief Description
Something is hanging on S3 Multipart in combination with Uppy. Events 'upload-success' and 'complete' do not fire on file upload...instead it fires if pause/ resume is clicked. This works fine on S3 version

### Expected behavior
A single file upload fires an 'upload-success' and 'complete' events with no intervention
### Actual behavior
File upload hangs at 100% completed with no response from multipart.

### Simplest self-contained example code to demonstrate issue
Is there a way to get logs of this other than in the console/ network tabs? I'm struggling with how to document - would love some advice.

plugins used: backgrounder, s3 presign_endpoint

Uppy Code:
```

 launchUppy() {
    const uppy = new Uppy({
      id: 'photoId' + this.photo.id,
      debug: false,
      allowMultipleUploads: false,
      autoProceed: true,
      restrictions: {
        allowedFileTypes: ['image/*'],
        maxNumberOfFiles: 1
      }
    })
      .use(Dashboard, {
        target: '.DashboardContainer',
        inline: true,
        trigger: '#drag-drop-area',
        replaceTargetContent: false,
        showProgressDetails: true,
        note: 'Upload file',
        disableThumbnailGenerator: true,
        height: 200
      })
      .use(S3Multipart, {
         limit: 1,
         companionUrl: this._api.getUrl('')
       })
      .use(Webcam, { target: Dashboard })
      .use(ScreenCapture, { target: Dashboard })
      .on('upload', result => {
        console.log('success ', result);
      })
      .on('upload-success', (file, result) => {
        console.log('file ', file);
        console.log('success ', result);
      })
      .on('upload-error', result => {
        console.log('error ', result);
      })
      .on('complete', result => {
        this.uploaded.emit(result.successful[0]);

        console.log('successful files:', result.successful);
        console.log('failed files:', result.failed);
      });
  }
```

### System configuration
**Ruby version**: 2.6.3
**Rails version**: 6.0.0

**Shrine version**: 3.2.1

**Comment by BKSpurgeon** [comment]
Hi Vijay are you able to spin up a minimal rails/roda app for this? If you can, pls post it here. @goelinsights

**Comment by BKSpurgeon** [comment]
@goelinsights also try the following:

```ruby
uppy.use(Uppy.AwsS3Multipart, {
  companionUrl: '/',
})
```

(Assuming you are not using companion, and are not otherwise generating the upload url using JavaScript)

**Comment by goelinsights** [comment]
@BKSpurgeon whats the best way to post the rails app? github repo? or would a loom with the network tab open be better?

**Comment by BKSpurgeon** [comment]
Github repo would be easiest to reproduce the problem. ( I'm unfamiliar with loom - this is a screen sharing software?)
