### ISSUE TITLE
After persist callbacks for Shrine 3

### ISSUE THREAD

**Issue by Aryk** [shrinerb/shrine#498]
What is the recommended way to run an after upload/persist callback with Shrine? Obviously you can overwrite the persist method and call super on it. Is there anything out of the box? Calling another db.after_commit from my experience doesn't guarantee that the file is uploaded when that block is called.

**Comment by janko** [comment]
I generally consider callbacks to be an anti-pattern, and while Shrine integrates with ActiveRecord/Sequel callbacks for ease of use, I don't plan on adding any Shrine-specific callbacks.

I would recommend putting any additional behaviour you want to perform around file attachments into service objects.

**Comment by jrochkind** [comment]
There is a common need to trigger logic after promotion though. 

I haven't figured out a good way to use 'service objects' to trigger logic after promotion (only after commit that has finalized a promotion), especially when you need it to be triggered whether or not you are using backgrounding. (Or if using backgrounding plugin, whether or not you've [temporarily disabled backgrounding](https://shrinerb.com/docs/plugins/backgrounding#disabling-backgrounding))

If anyone has arrived at a good convenient pattern for this common use case, it would be helpful to share it, perhaps eventually for inclusion as an example in some docs. I believe it is a common need, that is currently probably one of the things shrine users are mostly likely to be stumped by.

**Comment by janko** [comment]
@jrochkind The specific callback you asked for – after promotion but before persisting – wasn't requested in this issue. That one is easy to add, as `Attacher#promote` is part of the core. Doing something after persistence is more complicated, though, as it depends on the persistence plugins (`activerecord`, `sequel`).
