### ISSUE TITLE
Pdf not loading using docker-compose

### ISSUE THREAD

**Issue by goelinsights** [shrinerb/shrine#499]
### Brief Description
Trying to create derivative (thumbnails) of PDF with a multi-stage docker-compose setup. Getting "VipsForeignLoad: "/tmp/shrine20200904-1-13d7xwu.pdf" is not a known file format"

### Expected behavior
Able to use ImageProcessing gem to load PDF and process JPEG thumbnails.

### Actual behavior
Error loading the PDF
```
Traceback (most recent call last):
        2: from (irb):1
        1: from app/uploaders/brochure_uploader.rb:53:in `block in <class:BrochureUploader>'
Vips::Error (VipsForeignLoad: "/tmp/shrine20200904-1-13d7xwu.pdf" is not a known file format)
VipsForeignLoad: "/tmp/shrine20200904-1-13d7xwu.pdf" is not a known file format
```

### Simplest self-contained example code to demonstrate issue
```
from brochure_uploader.rb
Attacher.derivatives do |original|
    vips = ImageProcessing::Vips.source(original)
    
    starter = vips.loader(page: 0).resize_to_fit(3000, nil).convert("jpeg")
    
 
    # generate the thumbnails you want here 
    { 
      thumb:  starter.saver(quality: 70).resize_to_limit!(150, 225),
      square_300_h: starter.saver(quality: 80).resize_to_fill!(300, 301),
      w_1000_h: starter.saver(quality: 80).resize_to_limit!(1000, nil),
      w_2500_h: starter.saver(quality: 90).resize_to_limit!(2500, nil),
    }
  end
```

and libraries loaded in the Dockerfile. I had thought that adding poppler would have supplied the necessary PDF file loading support, but it doesn't appear to work
```
# Stage Final
FROM ruby:2.6.3-alpine
RUN apk add --update --no-cache \
  bash \
  postgresql-client \
  vips \
  poppler-glib \
  tzdata \
  imagemagick \
  jpegoptim
```
### System configuration
**Ruby version**: 2.6.3

**Shrine version**: 3.2.2

**Comment by janko** [comment]
Have you tried loading a PDF directly using `ruby-vips`? It's most likely not an issue with ImageProcessing gem, but ruby-vips/libvips itself, that it doesn't have PDF support. Personally I don't know what's exactly necessary in order to install libvips with PDF support, you'll have to find that out from the libvips maintainer or their installation guide.

Since this is not an issue with Shrine itself (ImageProcessing is a separate gem), I will close the issue.

**Comment by goelinsights** [comment]
If anyone comes across this in the future, I figured out that Vips wants the convert command to happen earlier in the chain (makes sense in hindsight).

```
Attacher.derivatives do |original|
    vips = ImageProcessing::Vips.source(original)    
    # generate the thumbnails you want here 
    { 
      thumb:  vips.convert("jpeg").call,
      square_300_h: vips.convert("jpeg").saver(quality: 80).resize_to_fill!(300, 301),
      w_1000_h: vips.convert("jpeg").saver(quality: 80).resize_to_fit!(1000, nil)
    }
  end
```
