### ISSUE TITLE
Unable to assign JSON data. InvalidFile error

### ISSUE THREAD

**Issue by balabis** [shrinerb/shrine#506]
As provided in the documentation, this is the default behaviour: 

<img width="804" alt="Screenshot 2020-11-13 at 22 54 48" src="https://user-images.githubusercontent.com/31573482/99120370-6ff4be80-2603-11eb-9d49-8c0635de6d00.png">

Assigning a json to the file field gets me an error `Shrine::InvalidFile ("...." is not a valid IO object (it doesn't respond to #read, #eof?, #rewind, #close))`

I did not assign in to a `_data` field, no. This is a sample I've got:
```
    document = Document.new
    document.user = current_user
    document.file = document_params[:file]
    document.number = document_params[:number]
    document.save
```
The way I managed to solve the issue was:
```
    document = Document.new
    document.user = current_user
    document.file_attacher.assign(document_params[:file])
    document.number = document_params[:number]
    document.save
```
By doing this way, the json was stored and immediately the file was promoted from the cache store and the entry in database was updated accordingly.

I would love to know what I am missing here, since as the documentation says, it should be possible to have it like that. 
I did find some similar issues here, but no solution so far.

**Shrine version**:
3.3.0

**Comment by janko** [comment]
Can you include your Shrine configuration?

**Comment by balabis** [comment]
```
require 'shrine'
require 'shrine/storage/s3'

s3_options = {
  access_key_id: Rails.application.credentials[:storage][:aws][:access_key_id],
  secret_access_key: Rails.application.credentials[:storage][:aws][:secret_access_key],
  region: Rails.application.credentials[:storage][:aws][:region],
  bucket: Rails.application.credentials[:storage][:aws][:bucket]
}

Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "#{Rails.env}/cache", **s3_options),
  store: Shrine::Storage::S3.new(prefix: Rails.env, **s3_options),
}

Shrine.plugin :activerecord
Shrine.plugin :uppy_s3_multipart

```

**Comment by janko** [comment]
I'm a bit surprised that's the whole configuration, maybe you didn't include plugins loaded just in your uploader? I wasn't able to reproduce it just with this. I've written a self-contained example below, using the configuration you provided, and assigning cached file data in Hash format works:

```rb
require "shrine"
require "shrine/storage/memory"
require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:documents) { |t| t.text :file_data }

Shrine.storages = {
  cache: Shrine::Storage::Memory.new,
  store: Shrine::Storage::Memory.new,
}

Shrine.plugin :activerecord
Shrine.plugin :uppy_s3_multipart

class FileUploader < Shrine
end

class Document < ActiveRecord::Base
  include FileUploader::Attachment(:file)
end

cached_file = FileUploader.upload(StringIO.new, :cache)
cached_file.data
# => {"id"=>"eb690bbe45a2bd4d61c2c16dddc7d257",
#     "storage"=>"cache",
#     "metadata"=>{"filename"=>nil, "size"=>0, "mime_type"=>nil}}

document = Document.new
document.file = cached_file.data
document.file # => #<FileUploader::UploadedFile storage=:cache id="eb690bbe45a2bd4d61c2c16dddc7d257" metadata={"filename"=>nil, "size"=>0, "mime_type"=>nil}>
```

**Comment by balabis** [comment]
Oh man... :man_facepalming: I have left this in the uploader class: `plugin :model, cache: false`
Sorry for wasting your time and a huge thanks for this great tool!
