### ISSUE TITLE
Keep original filename

### ISSUE THREAD

**Issue by dawidof** [shrinerb/shrine#521]
Please help, I need to keep original filename, but couldn't find any working solution

I have an uploader
```ruby
class S3FtpUploader < Shrine
  plugin :default_storage, cache: :s3_ftp_cache, store: :s3_ftp_store
  Shrine.logger = Rails.logger
  plugin :instrumentation
end
```

and using for upload
```ruby
s3_uploader = ::S3FtpUploader.new(:s3_ftp_store)
s3_uploader.upload(File.open(@local_path))
```

I've tried every solution from here, but none is working
https://github.com/shrinerb/shrine/issues/364

### System configuration
**Ruby version**: 2.7.1

**Shrine version**: 3.3.0

**Comment by benkoshy** [comment]
Hi Koval,

Pls clarify where it's failing if the following is off the mark?

https://shrinerb.com/docs/metadata

```ruby
upload_file = s3_uploader.upload(File.open(@local_path))

# original file name should be extracted by metadata
uploaded_file.metadata #=> 
# { 
#   "size" => 345993, 
#   "filename" => "matrix.mp4", 
#   "mime_type" => "video/mp4", 
# } 
## filename available in metadata
```

Or if you are using events then the metadata event should contain the filename in the payload?

**Comment by dawidof** [comment]
Hi @benkoshy yes, it does contain, but I need the files on s3 to have their original names, to work directly from s3, but not processing back through rails or sth else. And now it contains just sequence of random characters.

**Comment by dawidof** [comment]
Found 2 solutions

```ruby 
class S3FtpUploader < Shrine
  plugin :default_storage, cache: :s3_ftp_cache, store: :s3_ftp_store
  Shrine.logger = Rails.logger
  plugin :instrumentation

  def generate_uid(io)
     File.basename(io)
  end
end
```

2nd
```ruby
class S3FtpUploader < Shrine
  plugin :default_storage, cache: :s3_ftp_cache, store: :s3_ftp_store
  Shrine.logger = Rails.logger
  plugin :instrumentation

  def generate_location(io, context = {})
     @filename = File.basename(extract_filename(io).to_s, '.*')
     extension   = ".#{io.extension}" if io.is_a?(UploadedFile) && io.extension
     extension ||= File.extname(metadata["filename"].to_s).downcase

    "#{@filename}#{extension}"
  end
end
```

**Comment by benkoshy** [comment]
@dawidof this solution may overwrite two files with the same name. If you wish this not to happen,  consider adding a random or unique component to those files.

Besr rgds

**Comment by dawidof** [comment]
Thank you @benkoshy, but in my case I'm adding files with unique names with date and time
