### ISSUE TITLE
Record association

### ISSUE THREAD

**Issue by SynthesisOne** [shrinerb/shrine#526]
Hi I need to get the parent of record but record fields are empty

I want to do something like that

```ruby
 def generate_location(io, record: nil, **context)
    identifier = "questions/#{record.answer.question_id}/answers/#{record.answer_id}/attachments/#{record.id}"
    pretty_location(io, record: record, identifier: identifier, **context)
  end
```
  
  is there a plugin or hack how can this be done?

**Comment by janko** [comment]
You can most likely fix this by changing the order of attributes, to have the Shrine attachment attribute assigned *last* during mass assignment. If you're using strong params in Rails, you can do that by moving the attachment attribute at the end of the list.

**Comment by SynthesisOne** [comment]
> You can most likely fix this by changing the order of attributes, to have the Shrine attachment attribute assigned _last_ during mass assignment. If you're using strong params in Rails, you can do that by moving the attachment attribute at the end of the list.

yes, now that works, thanks
