### ISSUE TITLE
Derivation enpoint without upload_redirect causes Heroku error H18

### ISSUE THREAD

**Issue by dvkch** [shrinerb/shrine#533]
### Brief Description

In an ImageUploader I used the `derivation_endpoint` plugin, configured with `prefix: 'derivation/image', upload: true, upload_storage: :derivatives`. Images are stored on S3 with a main `store` storage and a `derivatives` storage.

### Expected behavior

In my local dev environment everything goes well, I can use my on-the-fly derivations easily and the images are resized as they should, and images show up in my views.

### Actual behavior

Once pushed to Heroku (tested Free, Hobby or Standard 1X dynos), any call to `/derivation/image/...` raises an Heroku router error with the following message : 

```
2021-04-14T15:39:08.360231+00:00 heroku[router]: sock=backend at=error code=H18 desc="Server Request Interrupted" method=GET path="/derivation/image/original/redacted?&signature=redacted" host=redacted.herokuapp.com request_id=redacted fwd="redacted ip" dyno=web.1 connect=0ms service=921ms status=503 bytes= protocol=https
```

### Simplest self-contained example code to demonstrate issue

image_uploader.rb : 

```
require 'image_processing/mini_magick'

class ImageUploader < Shrine
  plugin :derivation_endpoint, prefix: 'derivation/image', upload: true, upload_storage: :derivatives
  plugin :store_dimensions, analyzer: :mini_magick
  plugin :determine_mime_type
  plugin :pretty_location
  plugin :derivatives
  plugin :validation
  plugin :validation_helpers

  Attacher.validate do
    validate_max_size 20 * 1024 * 1024, message: I18n.t('activerecord.validations.common.file_is_too_large', max_mb: 20)
    validate_mime_type ALLOWED_IMAGE_TYPES
  end

  derivation :original do |file|
    img = ImageProcessing::MiniMagick
            .source(file).loader(page: 0)

    png = Shrine::Plugins::DetermineMimeType::MimeTypeAnalyzer.new(:file).call(file) == 'image/png'
    img = img.convert('jpg').quality(70) unless png

    img.call
  end
end
```

routes.rb : 

```
mount ImageUploader.derivation_endpoint => '/derivation/image'
```

### Workaround

When adding `upload_redirect: true` to the endpoint configuration the images show up properly in the front, and it seems to be even better on a performance level. But when using `record.image.derivation_url(:original, filename: ..., disposition: 'attachment')`, since we are redirected to S3, the downloaded file doesn't have the proper filename.

I would expect the endpoint to work on Heroku without having to pass `upload_redirect: true`, or the redirection to support `filename:, disposition:`.

### System configuration

**Ruby version**: 2.6.6
**Rails version**: 6.0.3.4
**Shrine version**: 3.3.0
**Puma version**: 4.3.7

### Notes

If I can provide any supplemental information to help you investigate feel free to ask!

**Comment by janko** [comment]
What does the error H18 mean on Heroku? The runtime was just 921ms, which can't be too long. But perhaps that's not measuring the actual time it took to stream the file from S3?

You should be able to control the S3 filename by passing options to the AWS SDK via `:upload_options`:

```rb
require "content_disposition"

plugin :derivation_endpoint, upload_options: -> do
  { content_disposition: ContentDisposition.inline(options[:filename]) }
end
```

or `:upload_redirect_url_options`:

```rb
require "content_disposition"

plugin :derivation_endpoint, upload_redirect_url_options: -> do
  { response_content_disposition: ContentDisposition.inline(options[:filename]) }
end
```

I haven't actually tested the above.

**Comment by dvkch** [comment]
Okay, first of all, a HUGE thank you. I saw `upload_redirect_url_options` in the docs, but didn't realise you could use it in combination with `response_content_disposition`. I now have a perfectly usable solution. I would suggest putting this example in the docs, it works exactly as you wrote it, if you give the `filename` option in the `derivation_url` call.

Secondly, the Heroku H18 error seems to be that the router detects the server or client has interrupted the connexion before giving a response. In our case, the server, as seen in the error log. I think somehow the response given by the derivation endpoint messes with Heroku when returning content, but works alright when redirecting.

I have confirmed that the derivatives were properly created and saved to S3 before the H18 error occurred. Already having an existing derivative didn't seem to change the behaviour. No Rails logs appeared in the heroku logs, except from `Started GET "/derivation/image/...."`

I tried reading the `derivation_endpoint.rb` file, the method `file_reponse(file, env)` seems to be a good place to start, but I am not versed enough in Rack internals to try and debug this issue :/

**Comment by janko** [comment]
It's possible that Heroku doesn't handle streaming derivation results from the storage well, which as you saw can be solved by switching to redirects. Since changing the default for Shrine now would be backwards incompatible, I don't think there is much to do here.

If someone finds out the exact reason for this error, perhaps we could add some Heroku caveats to the documentation.
