### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by coding-chimp** [shrinerb/shrine#536]
Hey, are you by any chance planning to cut a new release soonish? We could really use this change for our upgrade to Ruby 3.

> `activerecord` – Fix keyword argument warning when adding errors with options (@janko)

We're pointing to main branch for now, but doing this always makes me slightly nervous. 😅 

Thanks for your amazing work by the way. 🙂

**Comment by janko** [comment]
I will cut a new release this week 👍🏻

**Comment by rince** [comment]
@janko 
Thanks for shrine gem!
I'm also looking forward to the next release to upgrade to Ruby 3.
When will it be released?

**Comment by janko** [comment]
Shrine 3.4.0 has been released 🤘🏻

**Comment by rince** [comment]
@janko 
Thank you so much! 🎉
