### ISSUE TITLE
Mirroring doesn't pass along which storage it's generating the pretty location for

### ISSUE THREAD

**Issue by jnylen** [shrinerb/shrine#538]
- Issues are for bug reports only.
- Have a question or unsure if it's a bug, then please inquire on the [forum](https://discourse.shrinerb.com).
---

### Brief Description
When generating the pretty location i'm not supplied with the storage that it's generating the pretty location for.

For example if I just want to use the filename for Cloudinary for legacy purposes and a long folder path for S3 that isn't possible.

### Expected behavior
I expect Mirroring to pass in the storage it's running for along to `generate_location`

### Actual behavior
It isn't.

### Simplest self-contained example code to demonstrate issue

```
  def generate_location(io, record: nil, name: nil, derivative: nil, **context)
    puts io.inspect
    puts record.inspect
    puts context.inspect
  end
```

returns

```
#<ActionDispatch::Http::UploadedFile:0x00007f697cb81c20 @tempfile=#<Tempfile:/tmp/RackMultipart20210507-137-u1kw01.mp4>, @original_filename="Andreas_v2_1920x1080-2.mp4", @content_type="video/mp4", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"Andreas_v2_1920x1080-2.mp4\"\r\nContent-Type: video/mp4\r\n">
#<Image id: nil, file: nil>
{:action=>:store, :metadata=>{"filename"=>"Andreas_v2_1920x1080-2.mp4", "size"=>2761217, "mime_type"=>"video/mp4"}}
```

logs:

```
Upload (3215ms) – {:storage=>:cloudinary, :location=>"uploads/image/file/67678/uploads/image/file/67678/55f36caa332516099c2a3d4217b3d8fb.mp4", :io=>CloudinaryUploader::UploadedFile, :upload_options=>{:resource_type=>"video"}, :uploader=>CloudinaryUploader}
Open (402ms) – {:storage=>:cloudinary, :location=>"uploads/image/file/67678/uploads/image/file/67678/55f36caa332516099c2a3d4217b3d8fb.mp4", :download_options=>{}, :uploader=>CloudinaryUploader}
Upload (403ms) – {:storage=>:s3, :location=>"uploads/image/file/67678/uploads/image/file/67678/55f36caa332516099c2a3d4217b3d8fb.mp4", :io=>CloudinaryUploader::UploadedFile, :upload_options=>{}, :uploader=>CloudinaryUploader}
```

### System configuration
**Ruby version**: 2.7.2

**Shrine version**: 3.3.0

**Comment by jnylen** [comment]
Never mind. Found out `@storage_key` is giving me what I want :)

**Comment by benkoshy** [comment]
Hey @jnylen, 

Would you be able to copy/paste your set up? Or what would make things super super easy is if you could demo the issue with a template: e.g.  https://github.com/benkoshy/debugging-shrine-example otherwise it is very difficult for me to investigate/track down without being able to reproduce the issue.

chrs
