### ISSUE TITLE
Determine Mime Type returns incorrect type for svgs when using fastimage

### ISSUE THREAD

**Issue by Bandes** [shrinerb/shrine#539]
### Brief Description
When using the `:fastimage` analyzer, the determine_mime_type plugin returns a mime type of `image/svg` for svg images instead of the correct type of `image/svg+xml`

### Expected behavior
Shrine should return a mime type of `image/svg+xml`

### Actual behavior
Shrine returns a mime type of `image/svg`

### Simplest self-contained example code to demonstrate issue
```
    it "returns image/svg+xml if the image is an svg" do
      io = StringIO.new
      io.puts <<-SVG
        <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" xml:space="preserve" version="1.1" viewBox="0 0 20 20">
          <g>
            <path d="M0.567016+10.1229L19.267+10.1229"/>
          </g>
        </svg>
        SVG
      assert_equal "image/svg+xml", @shrine.determine_mime_type(io)
    end
```
### System configuration
**Ruby version**: 2.6.6

**Shrine version**: 3.3.0

**Comment by janko** [comment]
Resolved by https://github.com/shrinerb/shrine/pull/540
