### ISSUE TITLE
Add support for Backblaze

### ISSUE THREAD

**Issue by doutatsu** [shrinerb/shrine#543]
I've been trying to integrate with Backblaze for quite a bit, but unable to do it with Shrine. The only way currently, is to do it through fog, but the fog-backblaze adapter is not well maintained and doesn't work with Shrine properly (unable to save transformations or use remote_url). 

Backblaze is a lot cheaper than all other alternatives, so it would be really beneficial to support it, as I don't want to use S3 again or other supported alternatives, like Google, as they are still _a lot_ more expensive. It would be amazing if you could add the support 🙏🏻

**Comment by ringofhealth** [comment]
yeah I started a thread on discourse about this

https://discourse.shrinerb.com/t/using-backblaze-s3-compatible-api-for-presigned-requests/377

but it would be nice to have a plugin to automatically handle the API request

**Comment by janko** [comment]
I will close this, as it's a feature request for a separate gem, which I as a maintainer don't have the capacity to work on.
