### ISSUE TITLE
Checksum Implementation

### ISSUE THREAD

**Issue by tke578** [shrinerb/shrine#555]
I don't see any checksum javascript implementation following this guide?
https://shrinerb.com/docs/direct-s3#checksums

**Comment by benkoshy** [comment]
It's difficult to debug your particular issue without seeing more code. I am using (a slightly modified) version of the code in the s3 guide and it is working successfully. If you could provide a reproducible code sample, or even a snippet, that would help inordinately:  or alternatively, the following should be helpful to you:  https://github.com/erikdahlstrand/shrine-rails-example - it is a sample rails application.

lastly, may i recommend posting to the [forum](https://discourse.shrinerb.com/) - for two reasons: (i) the maintainers prefer it, and (ii) you'll get more people viewing your problem and willing to help out.

> Thanks @janko! Also, while following the[direct S3 guide](https://github.com/shrinerb/shrine/wiki/Adding-Direct-S3-Uploads) with the checksum implementation(PUT request), the uppy file response from uppy does not contain a `file.meta['key']` Is that wrong?
