### ISSUE TITLE
NoMethodError - undefined method `<column>_url'

### ISSUE THREAD

**Issue by lunaisnotaboy** [shrinerb/shrine#560]
### Brief Description

Whenever I try to call `<column>_url` or other related methods, I get a NoMethodError.

This has happened across three different applications on two seperate machines, so I am *convinced* that it is nothing on my end.

### Expected behavior

I expected the functions to actually be there when I call them.

### Actual behavior

I receive a NoMethodError.

### Code Snippets

See [this](https://gist.github.com/lunaisnotaboy/c0d699d92c83c8af9aa3e9d8ee865398) gist for all required files.

### System configuration

**Ruby version**: 2.7.4
**Shrine version**: 3.4.0

**Comment by benkoshy** [comment]
Hi @lunaisnotaboy,

I was unable to reproduce your issue, given your template. 

Here is my script file: https://github.com/benkoshy/debugging-shrine-example/tree/no-method-error-topic

Perhaps I've made a mistake somewhere? IF you could amend it, that would be inordinately helpful. 

rgds

Ben

**Comment by lunaisnotaboy** [comment]
@benkoshy Of course! However, my development laptop is currently experiencing unrelated issues, so I will not be able to provide you with updated files until later today. Apologies.

**Comment by lunaisnotaboy** [comment]
@benkoshy As I was looking over the code, it turns out that I had forgot to put `Shrine.plugin :activerecord` in my `shrine.rb` file.

This was purely a misconfiguration error, and I apologize. Thank you for trying to help.
