### ISSUE TITLE
Support retries with remote_url

### ISSUE THREAD

**Issue by jeremylynch** [shrinerb/shrine#649]
We are successfully using the `remote_url`, however occasionally running into "remote file not found" errors. 

Is there a way we could pass a `retries` variable to the downloader? Or alternatively what is the recommended way to handle retries here?

**Comment by janko** [comment]
You can override the `:downloader` option to add your retry logic:

```rb
Shrine.plugin :remote_url, downloader: -> (url, **options) do
  # example using the retriable gem – https://github.com/kamui/retriable
  Retriable.retriable { Down.download(url, **options) }
end
```
