### ISSUE TITLE
Disabling cache is tricky

### ISSUE THREAD

**Issue by ixti** [shrinerb/shrine#654]
I want to store HTTP responses on S3. Here's simplified example that gives me problems:

``` ruby
class MyUploader < Shrine
  plugin :model, cache: false
end

class WebhookResponse < ApplicationRecord
  include MyUploader::Attachment[:payload, cache: nil, store: :webhooks_store]
end

WebhookResponse.create!(payload: StringIO.new("..."))
```

Changing `cache: nil` to `cache: :webhooks_store` causes uploader to duplicate payloads. The only workaround I've found is to:

* set `cache: :webhooks_store` (just to avoid `MethodNotFound` exception, when Shrine tries to call `@cache.to_sym`)
* use `WebhookResponse.create! { _1.payload_attacher.attach(StringIO.new("...")) }`

**Comment by ixti** [comment]
Alternative hack I've came with:

``` ruby
class MyUploader < Shrine
  plugin :model, cache: false

  Attacher.define_method(:cache)         { nil }
  Attacher.define_method(:cache_key)     { nil }
  Attacher.define_method(:attach_cached) { |*, **| raise NotImplementedError }
  Attacher.define_method(:cached?)       { |*, **| false }
end
```

**Comment by janko** [comment]
The intention behind the `cache: false` plugin option wasn't to allow disabling the cache storage entirely, just to skip using it. Note that if you leave `:cache` as default, it still don't seem to require the `:cache` storage to actually be set.
