### ISSUE TITLE
Using Shrine with Cloudflare R2 causes error Aws::S3::Errors::NotImplemented  - x-amz-tagging

### ISSUE THREAD

**Issue by dylandamsma** [shrinerb/shrine#662]
**Issue:**
I've implemented Shrine with Cloudflare R2 S3-compatible object storage. However, when uploading an image, I get this error back from Cloudflare: Aws::S3::Errors::NotImplemented (Header 'x-amz-tagging-directive' with value 'REPLACE' not implemented).

As per their documentation, this is indeed not yet implemented:
https://developers.cloudflare.com/r2/api/s3/api/

This issue only occurs when generating / using derivatives

**Question:**
Is it possible to use Shrine with R2 at the moment? Is it possible to disable or bypass this x-amz-tagging?

**Note:**
It's to note I saw a recent posted where another user was also using Cloudflare R2, which suggested to me it is in fact usable.

**Comment by hkdahal** [comment]
I've identified/narrowed down that this only occurs when using cache store in Cloudflare. This doesn't occur when when using cache store via Filesystem and uploading to Cloudflare store.

It'd be great if we can get similar behavior when using cache in Cloudflare.

**Comment by hkdahal** [comment]
@dylandamsma - I've opened a PR to fix this: https://github.com/shrinerb/shrine/pull/663. In the meantime, I'm using this forked version (https://github.com/nebham/shrine) in my code.

**Comment by manuca** [comment]
I also faced this issue. No derivatives, just using R2 for cache and store. 

If I cache on the filesystem and store on R2 it does work.

BTW I also realized R2 doesn't support direct uploads via POST requests unfortunately. For folks looking to use that feature that Shrine supports for S3.

**Comment by thatdom** [comment]
+1

**Comment by janko** [comment]
Should be fixed by https://github.com/shrinerb/shrine/pull/663.

**Comment by legendetm** [comment]
We use shrinerb and s3 to upload files to AWS, Google and Alibaba, and we also had to disable the `X-Amz-Tagging`. So it's seems the tagging option is not implemented in multiple S3 compatible providers.

As the error message is general "NotImplemented - A header you provided implies functionality that is not implemented", maybe it would be good to add some notes to README, that if non AWS provider is used and you get NotImplemented error, you may need to disable tagging directive.

**Comment by jrochkind** [comment]
I wonder if it would make sense to create additional adapters for "S3-kind-of-compatible", either for specific ones or a general one with common things discovered in common?  It could certainly be done in another repo as a "third party" if someone were interested!

**Comment by legendetm** [comment]
For me the only issue with S3 compatible storage providers have been the `tagging-directive` for basic usage.

I would recommend to either make it opt-in or mention that in README, as I understand this is not supported by multiple S3-kind-of-compatible providers. Also It would be nice to mention this as possible breaking change in CHANGELOG for S3-kind-of-compatible providers.

Internally we check if s3 endpoint is given, and if then we remove the `tagging_directive` option.

**Comment by itisdoyoonkim** [comment]
Is this issue actually resolved? I am encountering the same issue as of today...

**Comment by legendetm** [comment]
@itisdoyoonkim - I'm handling this in our code in following way
```ruby
s3_options = { ... }
if s3_options[:endpoint].present? && Shrine.version >= '3.6.0'
  s3_options[:copy_options] = Shrine::Storage::S3::COPY_OPTIONS.except(:tagging_directive)
end
Shrine::Storage::S3.new(**s3_options)
```
In our case, we are using multiple different cloud storage providers depending on our clients. Some are using AWS S3, but not all of them and with this change it is working for all.

**Comment by jayelkaake** [comment]
FYI for anyone else who stumbles on this and wants summary, to solve the issue on Cloudflare R2:
1. Update to the latest Shrine (v3.6+)
2. Update your storages (`Shrine::Storage::S3` instances) to include `copy_options: {}`. For example, the docs change to:
```ruby
Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", copy_options: {}, **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", copy_options: {}, **s3_options)
}
