### ISSUE TITLE
 WARN: Job arguments to PromoteJob do not serialize to JSON safely. This will raise an error in Sidekiq 7.0.

### ISSUE THREAD

**Issue by QuentinRoadstr** [shrinerb/shrine#673]
Hi
According to the [documentation](https://shrinerb.com/docs/plugins/backgrounding#setup), we could pass file_data as argument but as reported in the title, this will raise an error : 
"Job arguments to PromoteJob do not serialize to JSON safely. This will raise an error in Sidekiq 7.0."

More information here : 
https://github.com/sidekiq/sidekiq/wiki/Best-Practices

Could documentation suggest another way to make it ? I think transmitting the temporary path of the file_data could be a fix.

**Comment by jrochkind** [comment]
(I'm not a maintainer, just a peer)

Can you check and see what `file_data` actually is?  I'm surprised it's not already json-able, and I wonder if it might be close.

**Comment by janko** [comment]
Note sure what exactly isn't serializable to JSON here, could you post all the arguments?
