### ISSUE TITLE
heroku - rails 5.2. - paperclip -> shrine

### ISSUE THREAD

**Issue by danielavdh** [shrinerb/shrine#681]
I have also written to heroku about this, since it is not in my power to find out where the problem lies:
I am upgrading rails 5.2.8.1 (ruby 2.6.10) apps, and before I start with that, I switch from paperclip to shrine. No problems. I can upload from development to the same aws s3 bucket as before, all fine.
When I deploy, I can't upload files from production to said s3 bucket.
I have turned every stone, as it makes no sense.
Then I give up, start a new app, copy all the app's files, create a new app on heroku and deploy. Except for the name of the app, everything is exactly the same.
Now file uploading from production (to the same bucket) works without a hitch.
Daniela

**Comment by janko** [comment]
Without information on errors you were getting I won't be able to help. I will close this issue in the meanwhile.
